### ISSUE TITLE
Flaky test: TestGetTaskByArn

### ISSUE THREAD

**Issue by samuelkarp** [aws/amazon-ecs-agent#1028]
### Summary
`TestGetTaskByArn` sometimes fails asynchronously after completion.

### Description
There appears to be a call to `MockDockerClient.CreateContainer`, which I think would be unexpected.  Possibly state is being leaked between tests.

### Expected Behavior
Tests pass.

### Observed Behavior
Tests fail sometimes.

### Environment Details
TravisCI

### Supporting Log Snippets
```
panic: Fail in goroutine after TestGetTaskByArn has completed

goroutine 11887 [running]:
panic(0xac1d00, 0xc42057eab0)
/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1ae
testing.(*common).Fail(0xc4201c4000)
/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:412 +0x182
testing.(*common).FailNow(0xc4201c4000)
/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:431 +0x39
testing.(*common).Fatalf(0xc4201c4000, 0xb98f7e, 0x2e, 0xc420620280, 0x5, 0x5)
/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:496 +0x95
testing.(*T).Fatalf(0xc4201c4000, 0xb98f7e, 0x2e, 0xc420620280, 0x5, 0x5)
<autogenerated>:12 +0x87
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/golang/mock/gomock.(*Controller).Call(0xc42056a020, 0xb68660, 0xc42057e030, 0xb87c65, 0xf, 0xc420458640, 0x4, 0x4, 0x0, 0x0, ...)
/home/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/golang/mock/gomock/controller.go:132 +0x734
github.com/aws/amazon-ecs-agent/agent/engine.(*MockDockerClient).CreateContainer(0xc42057e030, 0xc4201fc380, 0xc420037400, 0xc420580960, 0x28, 0x37e11d6000, 0x0, 0x0, 0x0, 0x0, ...)
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/engine_mocks.go:227 +0x281
github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).createContainer(0xc420682120, 0xc420412000, 0xc4206d2340, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/docker_task_engine.go:794 +0x107c
github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).(github.com/aws/amazon-ecs-agent/agent/engine.createContainer)-fm(0xc420412000, 0xc4206d2340, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/docker_task_engine.go:142 +0x9b
github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).applyContainerState(0xc420682120, 0xc420412000, 0xc4206d2340, 0xc400000002, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/docker_task_engine.go:1073 +0x35b
github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).transitionContainer(0xc420682120, 0xc420412000, 0xc4206d2340, 0xc400000002)
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/docker_task_engine.go:1043 +0x91
github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).progressContainers.func1(0xc4206d2340, 0xc400000002)
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/task_manager.go:487 +0xbb
created by github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).startContainerTransitions
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/task_manager.go:536 +0x20f
FAIL github.com/aws/amazon-ecs-agent/agent/engine 12.366s
```

**Comment by samuelkarp** [comment]
Closing since https://github.com/aws/amazon-ecs-agent/pull/1030 was merged.
