### ISSUE TITLE
Flaky test: TestManyDones

### ISSUE THREAD

**Issue by samuelkarp** [aws/amazon-ecs-agent#1055]
### Summary
`TestManyDones` is timing out sometimes.

### Description
```
=== RUN   TestManyDones
panic: test timed out after 25s
```

### Expected Behavior
Tests pass

### Observed Behavior
Tests fail, sometimes

### Supporting Log Snippets
```
=== RUN   TestManyDones
panic: test timed out after 25s

goroutine 704 [running]:
testing.startAlarm.func1()
        /usr/lib/golang/src/testing/testing.go:1023 +0x139
created by time.goFunc
        /usr/lib/golang/src/time/sleep.go:170 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42005e340, 0x5cf21c, 0xd, 0x5d6978, 0xc420047b01)
        /usr/lib/golang/src/testing/testing.go:698 +0x582
testing.runTests.func1(0xc42005e340)
        /usr/lib/golang/src/testing/testing.go:882 +0xab
testing.tRunner(0xc42005e340, 0xc420047ce8)
        /usr/lib/golang/src/testing/testing.go:657 +0x108
testing.runTests(0xc42000ca80, 0x6a5960, 0x2, 0x2, 0x148)
        /usr/lib/golang/src/testing/testing.go:888 +0x4e1
testing.(*M).Run(0xc420047f28, 0xc420047e40)
        /usr/lib/golang/src/testing/testing.go:822 +0x1c4
main.main()
        github.com/aws/amazon-ecs-agent/agent/utils/sync/_test/_testmain.go:90 +0x33e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2197 +0x1

goroutine 8 [runnable]:
github.com/aws/amazon-ecs-agent/agent/utils/sync.TestManyDones(0xc42005e4e0)
        /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/utils/sync/sequential_waitgroup_test.go:58 +0x1ad
testing.tRunner(0xc42005e4e0, 0x5d6978)
        /usr/lib/golang/src/testing/testing.go:657 +0x108
created by testing.(*T).Run
        /usr/lib/golang/src/testing/testing.go:697 +0x544

goroutine 9 [chan send]:
github.com/aws/amazon-ecs-agent/agent/utils/sync.TestManyDones.func1(0xc42000cae0, 0xc420018ba0, 0x1)
        /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/utils/sync/sequential_waitgroup_test.go:52 +0x6c
created by github.com/aws/amazon-ecs-agent/agent/utils/sync.TestManyDones
        /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/utils/sync/sequential_waitgroup_test.go:53 +0x116

goroutine 10 [chan send]:
github.com/aws/amazon-ecs-agent/agent/utils/sync.TestManyDones.func1(0xc42000cae0, 0xc420018c00, 0x2)
        /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/utils/sync/sequential_waitgroup_test.go:52 +0x6c
created by github.com/aws/amazon-ecs-agent/agent/utils/sync.TestManyDones
        /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/utils/sync/sequential_waitgroup_test.go:53 +0x116

goroutine 11 [chan send]:
github.com/aws/amazon-ecs-agent/agent/utils/sync.TestManyDones.func1(0xc42000cae0, 0xc420018c60, 0x3)
        /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/utils/sync/sequential_waitgroup_test.go:52 +0x6c
created by github.com/aws/amazon-ecs-agent/agent/utils/sync.TestManyDones
        /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/utils/sync/sequential_waitgroup_test.go:53 +0x116

goroutine 12 [chan send]:
github.com/aws/amazon-ecs-agent/agent/utils/sync.TestManyDones.func1(0xc42000cae0, 0xc420018cc0, 0x4)
        /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/utils/sync/sequential_waitgroup_test.go:52 +0x6c
created by github.com/aws/amazon-ecs-agent/agent/utils/sync.TestManyDones
        /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/utils/sync/sequential_waitgroup_test.go:53 +0x116

[repeats up to goroutine 702 with the same stack]

goroutine 703 [semacquire]:
sync.runtime_notifyListWait(0xc4200530d0, 0x4)
        /usr/lib/golang/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4200530c0)
        /usr/lib/golang/src/sync/cond.go:57 +0x97
github.com/aws/amazon-ecs-agent/agent/utils/sync.(*SequentialWaitGroup).Wait(0xc42000cae0, 0x2b6)
        github.com/aws/amazon-ecs-agent/agent/utils/sync/_test/_obj_test/sequential_waitgroup.go:96 +0x1ac
github.com/aws/amazon-ecs-agent/agent/utils/sync.TestManyDones.func1(0xc42000cae0, 0xc42028b080, 0x2b6)
        /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/utils/sync/sequential_waitgroup_test.go:51 +0x43
created by github.com/aws/amazon-ecs-agent/agent/utils/sync.TestManyDones
        /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/utils/sync/sequential_waitgroup_test.go:53 +0x116

```

(the rest is elided, but is available in our S3 bucket for commit 78747a6b709f6ff3b2c452b259c8590ae3ea78c8)

**Comment by yunhee-l** [comment]
[PR](https://github.com/aws/amazon-ecs-agent/pull/1132) submitted

**Comment by yunhee-l** [comment]
PR merged.
