### ISSUE TITLE
Update go-winio to get rid of the runtime error

### ISSUE THREAD

**Issue by richardpen** [aws/amazon-ecs-agent#1091]
### Summary

The integration test occasionally fail due to a runtime error, which seems have been fixed in Microsoft/go-winio#48

### Description

```
2017-11-17T23:19:20Z [INFO] Created container name mapping for task imgClean - test3 -> ecs-imgClean-1-test3-aa83d9a79a9d919c0e00
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x1 addr=0xa41110 pc=0x4392e6]

goroutine 9727 [running]:
runtime.throw(0xae7458, 0x2a)
	C:/Go/src/runtime/panic.go:605 +0x9c fp=0xc0422b7e20 sp=0xc0422b7e00 pc=0x4674cc
runtime.sigpanic()
	C:/Go/src/runtime/signal_windows.go:155 +0x184 fp=0xc0422b7e50 sp=0xc0422b7e20 pc=0x47e494
runtime.(*waitq).enqueue(0xc0420ece28, 0xc0424bc600)
	C:/Go/src/runtime/chan.go:686 +0x76 fp=0xc0422b7e80 sp=0xc0422b7e50 pc=0x4392e6
runtime.chansend(0xc0420ecde0, 0xc0422b7fb0, 0x1, 0x89a5e4, 0xc0422b7f90)
	C:/Go/src/runtime/chan.go:221 +0x278 fp=0xc0422b7f18 sp=0xc0422b7e80 pc=0x437c28
runtime.chansend1(0xc0420ecde0, 0xc0422b7fb0)
	C:/Go/src/runtime/chan.go:113 +0x43 fp=0xc0422b7f50 sp=0xc0422b7f18 pc=0x4379a3
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x124)
	c:/Users/Administrator/workspace/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/Microsoft/go-winio/file.go:131 +0xa4 fp=0xc0422b7fd8 sp=0xc0422b7f50 pc=0x89a5e4
runtime.goexit()
	C:/Go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc0422b7fe0 sp=0xc0422b7fd8 pc=0x499641
created by github.com/aws/amazon-ecs-agent/agent/vendor/github.com/Microsoft/go-winio.initIo
	c:/Users/Administrator/workspace/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/Microsoft/go-winio/file.go:55 +0xaf
```

**Comment by richardpen** [comment]
This is done in #1097
