### ISSUE TITLE
Initialize the member in resource during unmarshal

### ISSUE THREAD

**Issue by richardpen** [aws/amazon-ecs-agent#1413]
### Summary

When the agent restart, the resource struct is recovered from the state file, but the object inside the struct isn't initialized, so it will panic if you try to use it.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x92d3af]

goroutine 229 [running]:
github.com/aws/amazon-ecs-agent/agent/taskresource/cgroup.(*CgroupResource).Cleanup(0xc420229600, 0xc4202ff740, 0x2)
	/go/src/github.com/aws/amazon-ecs-agent/agent/taskresource/cgroup/cgroup.go:273 +0x3f
github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).deleteTask(0xc4202d78c0, 0xc420358000)
	/go/src/github.com/aws/amazon-ecs-agent/agent/engine/docker_task_engine.go:458 +0x9e
github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).cleanupTask(0xc420185ee0, 0xdf8475800)
	/go/src/github.com/aws/amazon-ecs-agent/agent/engine/task_manager.go:1074 +0x29f
github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).overseeTask(0xc420185ee0)
	/go/src/github.com/aws/amazon-ecs-agent/agent/engine/task_manager.go:246 +0x2ed
created by github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).startTask
	/go/src/github.com/aws/amazon-ecs-agent/agent/engine/docker_task_engine.go:507 +0x9c
```

**Comment by yunhee-l** [comment]
Fix already merged. Resolving.
