### ISSUE TITLE
Flaky test: TestEmptyHostVolumeMount

### ISSUE THREAD

**Issue by haikuoliu** [aws/amazon-ecs-agent#1488]
### Summary

`TestEmptyHostVolumeMount` sometimes fails.

### Expected Behavior
Test passes

### Observed Behavior
Test fails sometimes

### Environment Details
EC2 instance.

### Supporting Log Snippets

```
=== RUN   TestEmptyHostVolumeMount
2018-07-26T20:36:19Z [CRITICAL] Unable to communicate with EC2 Metadata service to infer region: blackholed
2018-07-26T20:36:19Z [CRITICAL] Configuration key not set, key: AWSRegion
2018-07-26T20:36:19Z [INFO] Managed task [testEmptyHostVolumeMount]: unable to create task state change event []: create task state change event api: status not recognized by ECS: NONE
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: pulling container test2 concurrently
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: Recording timestamp for starting image pulltime: 2018-07-26 20:36:19.044599602 +0000 UTC m=+169.153652660
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: pulling container netcat concurrently
2018-07-26T20:36:19Z [INFO] Adding image name- 127.0.0.1:51670/amazon/amazon-ecs-volumes-test:latest to Image state- sha256:8b37d1463d6169feb530e325fe18ff9e0db63a523e503048d0a3b0005b3a744e
2018-07-26T20:36:19Z [INFO] Updating container reference test2 in Image State - sha256:8b37d1463d6169feb530e325fe18ff9e0db63a523e503048d0a3b0005b3a744e
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: Finished pulling container 127.0.0.1:51670/amazon/amazon-ecs-volumes-test:latest in 62.349044ms
2018-07-26T20:36:19Z [INFO] Updating container reference netcat in Image State - sha256:8b37d1463d6169feb530e325fe18ff9e0db63a523e503048d0a3b0005b3a744e
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: Finished pulling container 127.0.0.1:51670/amazon/amazon-ecs-volumes-test:latest in 62.360003ms
2018-07-26T20:36:19Z [WARN] Managed task [testEmptyHostVolumeMount]: failed to write container [test2] change event to tcs event stream: Event stream is closed
2018-07-26T20:36:19Z [WARN] Managed task [testEmptyHostVolumeMount]: failed to write container [netcat] change event to tcs event stream: Event stream is closed
2018-07-26T20:36:19Z [WARN] Managed task [testEmptyHostVolumeMount]: failed to write container [~internal~ecs-emptyvolume-source] change event to tcs event stream: Event stream is closed
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: creating container: ~internal~ecs-emptyvolume-source
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: created container name mapping for task:  ~internal~ecs-emptyvolume-source -> ecs-family-1-internalecs-emptyvolume-source-c0d1ceaabff0a1ffcf01
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: created docker container for task: ~internal~ecs-emptyvolume-source -> a8d9be357b37cdcb1766f918093d9486fd3e6f477b6f9b975dcf54c9e39a66ea
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: created docker container for task: ~internal~ecs-emptyvolume-source -> a8d9be357b37cdcb1766f918093d9486fd3e6f477b6f9b975dcf54c9e39a66ea, took 242.342409ms
2018-07-26T20:36:19Z [WARN] Managed task [testEmptyHostVolumeMount]: failed to write container [~internal~ecs-emptyvolume-source] change event to tcs event stream: Event stream is closed
2018-07-26T20:36:19Z [INFO] Managed task [testEmptyHostVolumeMount]: redundant container state change. ~internal~ecs-emptyvolume-source to CREATED, but already CREATED
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: starting container: ~internal~ecs-emptyvolume-source
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: started docker container for task: ~internal~ecs-emptyvolume-source -> a8d9be357b37cdcb1766f918093d9486fd3e6f477b6f9b975dcf54c9e39a66ea, took 372.17072ms
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: error transitioning container [~internal~ecs-emptyvolume-source] to [RUNNING]: API error (400): OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"not-applicable\": executable file not found in $PATH": unknown

2018-07-26T20:36:19Z [WARN] Managed task [testEmptyHostVolumeMount]: error starting/provisioning container[~internal~ecs-emptyvolume-source]; marking its desired status as STOPPED: API error (400): OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"not-applicable\": executable file not found in $PATH": unknown

2018-07-26T20:36:19Z [WARN] Managed task [testEmptyHostVolumeMount]: failed to write container [~internal~ecs-emptyvolume-source] change event to tcs event stream: Event stream is closed
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: creating container: netcat
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: creating container: test2
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: created container name mapping for task:  netcat -> ecs-family-1-netcat-a6a4c1cdd0b2f8d79801
2018-07-26T20:36:19Z [INFO] Task engine [testEmptyHostVolumeMount]: created container name mapping for task:  test2 -> ecs-family-1-test2-a2c4a3db93a281b13c00
2018-07-26T20:36:20Z [INFO] Task engine [testEmptyHostVolumeMount]: created docker container for task: netcat -> 3630ac0b6bd1a92a02d852eec727c9907318e500b14603078ec979c5c44ce80e
2018-07-26T20:36:20Z [INFO] Task engine [testEmptyHostVolumeMount]: created docker container for task: netcat -> 3630ac0b6bd1a92a02d852eec727c9907318e500b14603078ec979c5c44ce80e, took 380.050995ms
2018-07-26T20:36:20Z [WARN] Managed task [testEmptyHostVolumeMount]: failed to write container [netcat] change event to tcs event stream: Event stream is closed
2018-07-26T20:36:20Z [INFO] Managed task [testEmptyHostVolumeMount]: redundant container state change. netcat to CREATED, but already CREATED
2018-07-26T20:36:20Z [INFO] Task engine [testEmptyHostVolumeMount]: starting container: netcat
2018-07-26T20:36:20Z [INFO] Task engine [testEmptyHostVolumeMount]: created docker container for task: test2 -> 57b9c0c998fc7941278f488beb89d45ba94080da4cd84a5f5f8e99c6c6e799f9
2018-07-26T20:36:20Z [INFO] Task engine [testEmptyHostVolumeMount]: created docker container for task: test2 -> 57b9c0c998fc7941278f488beb89d45ba94080da4cd84a5f5f8e99c6c6e799f9, took 555.364749ms
2018-07-26T20:36:20Z [WARN] Managed task [testEmptyHostVolumeMount]: failed to write container [test2] change event to tcs event stream: Event stream is closed
2018-07-26T20:36:20Z [INFO] Managed task [testEmptyHostVolumeMount]: unable to create task state change event []: create task state change event api: status not recognized by ECS: CREATED
2018-07-26T20:36:20Z [INFO] Task engine [testEmptyHostVolumeMount]: starting container: test2
2018-07-26T20:36:20Z [INFO] Task engine [testEmptyHostVolumeMount]: started docker container for task: netcat -> 3630ac0b6bd1a92a02d852eec727c9907318e500b14603078ec979c5c44ce80e, took 311.007474ms
2018-07-26T20:36:20Z [WARN] Managed task [testEmptyHostVolumeMount]: failed to write container [netcat] change event to tcs event stream: Event stream is closed
2018-07-26T20:36:20Z [INFO] Managed task [testEmptyHostVolumeMount]: sending container change event [netcat]: testEmptyHostVolumeMount netcat -> RUNNING, Known Sent: NONE
2018-07-26T20:36:20Z [INFO] Managed task [testEmptyHostVolumeMount]: sent container change event [netcat]: testEmptyHostVolumeMount netcat -> RUNNING, Known Sent: NONE
2018-07-26T20:36:20Z [INFO] Managed task [testEmptyHostVolumeMount]: redundant container state change. netcat to RUNNING, but already RUNNING
2018-07-26T20:36:21Z [INFO] Task [testEmptyHostVolumeMount]: recording execution stopped time. Essential container [netcat] stopped at: 2018-07-26 20:36:21.248078531 +0000 UTC m=+171.357131628
2018-07-26T20:36:21Z [WARN] Managed task [testEmptyHostVolumeMount]: failed to write container [netcat] change event to tcs event stream: Event stream is closed
2018-07-26T20:36:21Z [INFO] Managed task [testEmptyHostVolumeMount]: sending container change event [netcat]: testEmptyHostVolumeMount netcat -> STOPPED, Exit 42, , Known Sent: NONE
2018-07-26T20:36:21Z [INFO] Managed task [testEmptyHostVolumeMount]: sent container change event [netcat]: testEmptyHostVolumeMount netcat -> STOPPED, Exit 42, , Known Sent: NONE
2018-07-26T20:36:21Z [WARN] Managed task [testEmptyHostVolumeMount]: failed to write container [test2] change event to tcs event stream: Event stream is closed
2018-07-26T20:36:21Z [INFO] Managed task [testEmptyHostVolumeMount]: sending container change event [test2]: testEmptyHostVolumeMount test2 -> STOPPED, Known Sent: NONE
2018-07-26T20:36:21Z [INFO] Managed task [testEmptyHostVolumeMount]: sent container change event [test2]: testEmptyHostVolumeMount test2 -> STOPPED, Known Sent: NONE
--- FAIL: TestEmptyHostVolumeMount (2.24s)
	<autogenerated>:1: 
                        
	Error Trace:	common_integ_test.go:59
		
			engine_integ_test.go:186
		
	Error:		Not equal: 5 (expected)
			        != 3 (actual)
		
	Messages:	Expected container to be RUNNING
		
panic: interface conversion: statechange.Event is api.ContainerStateChange, not api.TaskStateChange [recovered]
	panic: interface conversion: statechange.Event is api.ContainerStateChange, not api.TaskStateChange

goroutine 2083 [running]:
testing.tRunner.func1(0xc420251a40)
	/usr/local/go/src/testing/testing.go:711 +0x5d9
panic(0xcd7320, 0xc420056380)
	/usr/local/go/src/runtime/panic.go:491 +0x2a2
github.com/aws/amazon-ecs-agent/agent/engine.verifyTaskRunningStateChange(0xc420251a40, 0x13bf580, 0xc42035a900)
	/opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/engine/engine_integ_test.go:68 +0x1c6
github.com/aws/amazon-ecs-agent/agent/engine.TestEmptyHostVolumeMount(0xc420251a40)
	/opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/engine/engine_integ_test.go:187 +0x24a
testing.tRunner(0xc420251a40, 0xdb7508)
	/usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x569
```

**Comment by richardpen** [comment]
I believe this was fixed in the 1.20.0 release, where we replaced the empty container with the local volume. Closing.
