### ISSUE TITLE
Docker corrupted

### ISSUE THREAD

**Issue by jeremybalog** [aws/amazon-ecs-agent#1698]
### Summary
ECS seems to corrupt docker somehow.  I can log into the ECS instance fine, but when I do a `docker ps` the whole thing blows up--the log snippet below is a stack trace.  This was never an issue running the same containers for the past year on 1) a previous agent version and 2) smaller instances.

### Description
I'm running `amzn-ami-2018.03.i-amazon-ecs-optimized (ami-045f1b3f87ed83659)` image on `c5.18xlarge` EC2 instances.  You can see that one instance is running containers fine--second is corrupted.  They are identical instances and it seems to only be a matter of time before the working one becomes corrupted with the same issue.

![image](https://user-images.githubusercontent.com/12202407/48732257-1ff9e180-ec0d-11e8-8cd5-c74433ee72ea.png)

The tasks end up in a perpetual state of pending as a result with no self healing.  The only way to fix the issue is destroy the instance and relaunch a fresh one.  Note the above screenshot says the agent is connected and watching these pending tasks never actually run.  The task example below has been pending for 3 hours:

![image](https://user-images.githubusercontent.com/12202407/48732544-fe4d2a00-ec0d-11e8-8075-611af3f9b795.png)

![image](https://user-images.githubusercontent.com/12202407/48732336-62bbb980-ec0d-11e8-8897-ce072285d4cc.png)

### Supporting Log Snippets

```
[ec2-user@ip-172-31-13-251 ~]$ docker ps
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7fc162f0f277 m=3 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fc162f0f277
stack: frame={sp:0x7fc1626d6958, fp:0x0} stack=[0x7fc161ed72b0,0x7fc1626d6eb0)
00007fc1626d6858:  0000000000000000  0000000000000000
00007fc1626d6868:  0000000000000000  0000000000000000
00007fc1626d6878:  0000000000000000  0000000000000000
00007fc1626d6888:  0000000000000000  0000000000000000
00007fc1626d6898:  0000000000000000  0000000000000000
00007fc1626d68a8:  0000000000000000  0000000000000000
00007fc1626d68b8:  0000000000000000  0000000000000000
00007fc1626d68c8:  0000000000000000  0000000000000000
00007fc1626d68d8:  0000000000000000  0000000000000000
00007fc1626d68e8:  0000000000000000  0000000000000000
00007fc1626d68f8:  0000000000000000  0000000000000000
00007fc1626d6908:  0000000000000000  0000000000000000
00007fc1626d6918:  0000000000000000  0000000000000000
00007fc1626d6928:  00007fc1632a0868  00000000019c6f1e
00007fc1626d6938:  00007fc15c0008c0  00000000000000f1
00007fc1626d6948:  0000000000000011  0000000000000000
00007fc1626d6958: <00007fc162f10968  0000000000000020
00007fc1626d6968:  0000000000000000  0000000000000000
00007fc1626d6978:  0000000000000000  0000000000000000
00007fc1626d6988:  0000000000000000  0000000000000000
00007fc1626d6998:  0000000000000000  0000000000000000
00007fc1626d69a8:  0000000000000000  0000000000000000
00007fc1626d69b8:  0000000000000000  0000000000000000
00007fc1626d69c8:  0000000000000000  0000000000000000
00007fc1626d69d8:  0000000000000000  000000000000000d
00007fc1626d69e8:  00007fc162fc8cf9  0000000000000000
00007fc1626d69f8:  00007fc162f530c3  000000000000000d
00007fc1626d6a08:  00007fc1632a01c0  0000000000000001
00007fc1626d6a18:  00007fc1632a0243  00007fc16329c3a0
00007fc1626d6a28:  00007fc162f548de  00007fc1632a01c0
00007fc1626d6a38:  000000000000000a  00007fc15c0008c0
00007fc1626d6a48:  00000000000000f1  0000000000000011
runtime: unknown pc 0x7fc162f0f277
stack: frame={sp:0x7fc1626d6958, fp:0x0} stack=[0x7fc161ed72b0,0x7fc1626d6eb0)
00007fc1626d6858:  0000000000000000  0000000000000000
00007fc1626d6868:  0000000000000000  0000000000000000
00007fc1626d6878:  0000000000000000  0000000000000000
00007fc1626d6888:  0000000000000000  0000000000000000
00007fc1626d6898:  0000000000000000  0000000000000000
00007fc1626d68a8:  0000000000000000  0000000000000000
00007fc1626d68b8:  0000000000000000  0000000000000000
00007fc1626d68c8:  0000000000000000  0000000000000000
00007fc1626d68d8:  0000000000000000  0000000000000000
00007fc1626d68e8:  0000000000000000  0000000000000000
00007fc1626d68f8:  0000000000000000  0000000000000000
00007fc1626d6908:  0000000000000000  0000000000000000
00007fc1626d6918:  0000000000000000  0000000000000000
00007fc1626d6928:  00007fc1632a0868  00000000019c6f1e
00007fc1626d6938:  00007fc15c0008c0  00000000000000f1
00007fc1626d6948:  0000000000000011  0000000000000000
00007fc1626d6958: <00007fc162f10968  0000000000000020
00007fc1626d6968:  0000000000000000  0000000000000000
00007fc1626d6978:  0000000000000000  0000000000000000
00007fc1626d6988:  0000000000000000  0000000000000000
00007fc1626d6998:  0000000000000000  0000000000000000
00007fc1626d69a8:  0000000000000000  0000000000000000
00007fc1626d69b8:  0000000000000000  0000000000000000
00007fc1626d69c8:  0000000000000000  0000000000000000
00007fc1626d69d8:  0000000000000000  000000000000000d
00007fc1626d69e8:  00007fc162fc8cf9  0000000000000000
00007fc1626d69f8:  00007fc162f530c3  000000000000000d
00007fc1626d6a08:  00007fc1632a01c0  0000000000000001
00007fc1626d6a18:  00007fc1632a0243  00007fc16329c3a0
00007fc1626d6a28:  00007fc162f548de  00007fc1632a01c0
00007fc1626d6a38:  000000000000000a  00007fc15c0008c0
00007fc1626d6a48:  00000000000000f1  0000000000000011

goroutine 1 [runnable, locked to thread]:
runtime.gcenable()
        /usr/lib/golang/src/runtime/mgc.go:214 +0x85
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:161 +0x11e
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2361 +0x1

rax    0x0
rbx    0x7fc1632a0868
rcx    0x7fc162f0f277
rdx    0x6
rdi    0xf444
rsi    0xd17d
rbp    0x19c6f1e
rsp    0x7fc1626d6958
r8     0xa
r9     0x7fc1626d7700
r10    0x8
r11    0x206
r12    0x7fc15c0008c0
r13    0xf1
r14    0x11
r15    0x0
rip    0x7fc162f0f277
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```

**Comment by petderek** [comment]
Hey @jeremybalog,

Sorry to hear about the trouble you are having while running tasks. I'd like to try to repro or debug this on my end, but I'll need a little more information.

What was the previous version of agent or ami you were using?

What was the previous instance type you were using?

Also, If you could send me the docker and agent log from an instance that got caught in this error state, that may help us debug. You can send them to me here: petderek at amazon dot com

**Comment by jeremybalog** [comment]
The previous agents were always edge, 1.19/20/21 on m5.2xlarge instances previously.  Things have been more stable recently, but next time things blow up I'll dump the logs.  Can you provide the exact files/paths for the logs you'd need to debug?

**Comment by jeremybalog** [comment]
I am unable to access any docker logs because docker commands don't work and `ec2-user` doesn't have permission to access the docker directories (even with sudo).  We have two instances and rebooting seemed to solve things for one of them (but not the long term issue).  The second says docker isn't even running when I log in (thus agent connected=false).  There needs to be some sort of self-healing happening here, but there isn't.

![image](https://user-images.githubusercontent.com/12202407/49178012-a9e82f80-f31c-11e8-933d-af69590331ae.png)

![image](https://user-images.githubusercontent.com/12202407/49178034-b8364b80-f31c-11e8-9bd1-7f2f76adf35b.png)

**Comment by petderek** [comment]
The logfiles that are most helpful are the directory `/var/log/ecs` and the file `/var/log/docker`.  We also have a [collection script here](https://github.com/awslabs/ecs-logs-collector) that gathers more information from the host.

On the second host, can you manually enable docker? Or does it throw an error? IE, `sudo service docker start`.

> ec2-user doesn't have permission to access the docker directories (even with sudo)

This shouldn't be the case. If you `sudo su` and then try to navigate to the directory, it should permit you. Which directory are you unable to access?

**Comment by samuelkarp** [comment]
@jeremybalog If you are not running a zombie-reaping init process within your container, we recommend setting the [`initProcessEnabled`](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_linuxparameters) field of the task definition to `true`.  When using this field, Docker will inject an init process ([tini](https://github.com/krallin/tini), by default) into your container to handle process reaping.  More information on the init process can be found in the [Docker `--init` documentation](https://docs.docker.com/engine/reference/run/#specify-an-init-process).

(Zombie processes may not get reaped in a container as the processes are contained within the container's `pid` namespace and are not effectively reparented to the init process running in the host `pid` namespace.  Running an init process within the container's `pid` namespace will cause zombies to be reparented to that process, which can then reap them.)

**Comment by jeremybalog** [comment]
@samuelkarp thank you for that--I thought I had it fixed, but seeing a bunch of zombie processes bubbling still.
