### ISSUE TITLE
testing: TestStateManager failing intermittently with timeouts

### ISSUE THREAD

**Issue by suneyz** [aws/amazon-ecs-agent#1856]
Flaky unit test. Sometimes it will timeout.

### Supporting Log Snippets

````
=== RUN   TestStateManager
2019-01-29T23:30:10Z [INFO] Loading state! module="statemanager"
2019-01-29T23:30:10Z [INFO] Saving state! module="statemanager"
panic: test timed out after 30s

goroutine 69 [running]:
testing.startAlarm.func1()
    /usr/local/go/src/testing/testing.go:1145 +0x139
created by time.goFunc
    /usr/local/go/src/time/sleep.go:170 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc420374000, 0xd5d0d4, 0x10, 0xd7db28, 0xc42024db01)
    /usr/local/go/src/testing/testing.go:790 +0x59b
testing.runTests.func1(0xc420374000)
    /usr/local/go/src/testing/testing.go:1004 +0xa8
testing.tRunner(0xc420374000, 0xc42024dd28)
    /usr/local/go/src/testing/testing.go:746 +0x16d
testing.runTests(0xc4202a10c0, 0x11da120, 0xb, 0xb, 0xc4200a2c48)
    /usr/local/go/src/testing/testing.go:1002 +0x522
testing.(*M).Run(0xc4204d1f20, 0x30)
    /usr/local/go/src/testing/testing.go:921 +0x207
main.main()
    github.com/aws/amazon-ecs-agent/agent/statemanager/_test/_testmain.go:118 +0x2f1

goroutine 5 [semacquire]:
sync.runtime_notifyListWait(0xc420057250, 0x0)
    /usr/local/go/src/runtime/sema.go:507 +0x11f
sync.(*Cond).Wait(0xc420057240)
    /usr/local/go/src/sync/cond.go:56 +0x8e
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc420162900, 0x0)
    /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x108
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc420162900)
    /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x52
created by github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.NewAsyncLoopLogger
    /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0xeb

goroutine 6 [semacquire]:
sync.runtime_notifyListWait(0xc4200573d0, 0x0)
    /usr/local/go/src/runtime/sema.go:507 +0x11f
sync.(*Cond).Wait(0xc4200573c0)
    /usr/local/go/src/sync/cond.go:56 +0x8e
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc420162a20, 0x0)
    /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x108
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc420162a20)
    /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x52
created by github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.NewAsyncLoopLogger
    /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0xeb

goroutine 7 [semacquire]:
sync.runtime_notifyListWait(0xc420057a50, 0x9)
    /usr/local/go/src/runtime/sema.go:507 +0x11f
sync.(*Cond).Wait(0xc420057a40)
    /usr/local/go/src/sync/cond.go:56 +0x8e
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc420162b40, 0x0)
    /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x108
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc420162b40)
    /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x52
created by github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.NewAsyncLoopLogger
    /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0xeb

goroutine 68 [syscall]:
syscall.Syscall(0x4a, 0x9, 0x0, 0x0, 0x18, 0xc4200ed808, 0x4c9ab4)
    /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Fsync(0x9, 0xd7ee28, 0xc42006a460)
    /usr/local/go/src/syscall/zsyscall_linux_amd64.go:473 +0x58
internal/poll.(*FD).Fsync(0xc42006a460, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_posix.go:56 +0xac
os.(*File).Sync(0xc4201da898, 0xc400000001, 0x1)
    /usr/local/go/src/os/file_posix.go:127 +0x69
github.com/aws/amazon-ecs-agent/agent/statemanager.(*basicStateManager).writeFile(0xc4200e8ee0, 0xc4203ad500, 0x27e, 0x33f, 0x33f, 0x0)
    github.com/aws/amazon-ecs-agent/agent/statemanager/_test/_obj_test/state_manager_unix.go:69 +0x38b
github.com/aws/amazon-ecs-agent/agent/statemanager.(*basicStateManager).ForceSave(0xc4200e8ee0, 0x0, 0x0)
    github.com/aws/amazon-ecs-agent/agent/statemanager/_test/_obj_test/state_manager.go:183 +0x37e
github.com/aws/amazon-ecs-agent/agent/statemanager.(*basicStateManager).Save(0xc4200e8ee0, 0x0, 0x0)
    github.com/aws/amazon-ecs-agent/agent/statemanager/_test/_obj_test/state_manager.go:145 +0x1b4
github.com/aws/amazon-ecs-agent/agent/statemanager_test.TestStateManager(0xc4201081e0)
    /opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/statemanager/state_manager_unix_test.go:58 +0x7ad
testing.tRunner(0xc4201081e0, 0xd7db28)
    /usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
    /usr/local/go/src/testing/testing.go:789 +0x569
*** Test killed: ran too long (1m30s).
FAIL    github.com/aws/amazon-ecs-agent/agent/statemanager    145.684s
````

**Comment by adnxn** [comment]
failure observed only on linux.

**Comment by petderek** [comment]
Its interesting that we don't see this failure on travis. We need to understand that failure mode

**Comment by fierlion** [comment]
It looks like we could be making a recursive call inside a locked block:
https://github.com/aws/amazon-ecs-agent/blob/master/agent/statemanager/state_manager.go#L220-L223 
we start manager.Save() with
```
manager.saveTimesLock.Lock()
defer manager.saveTimesLock.Unlock()
```

**Comment by fierlion** [comment]
More research: 
this wasn't related to the above.
Looks like this is related to 
https://github.com/aws/amazon-ecs-agent/blob/master/agent/statemanager/state_manager_unix.go
```
err = tmpfile.Sync()
```
where fsync is not returning.  
This issue went away when we shifted off of spinning disks to ssd.
