### ISSUE TITLE
Flaky Integ Test - TestShutdownOrder hangs occasionally

### ISSUE THREAD

**Issue by fenxiong** [aws/amazon-ecs-agent#1931]
### Summary

TestShutdownOrder hung occasionally. It doesn't look like we happen to reach timeout on this test from the total running time seen in logs.

### Expected Behavior
Test passes in ~20s.

### Observed Behavior
Test hung.

### Supporting Log Snippets

```
=== RUN   TestShutdownOrder
2019-03-08T01:16:19Z [INFO] Managed task [testDependencyHealthyTimeout]: redundant container state change. dependency to STOPPED, but already STOPPED
2019-03-08T01:16:19Z [INFO] Image excluded from cleanup: amazon/amazon-ecs-agent:latest
2019-03-08T01:16:19Z [INFO] Image excluded from cleanup: amazon/amazon-ecs-pause:0.1.0
2019-03-08T01:16:19Z [WARN] Unable to fetch user data: blackholed
2019-03-08T01:16:19Z [CRITICAL] Unable to communicate with EC2 Metadata service to infer region: blackholed
2019-03-08T01:16:19Z [CRITICAL] Configuration key not set, key: AWSRegion
2019-03-08T01:16:19Z [INFO] Unable to get Docker client for version 1.17: version detection using MinAPIVersion: unsupported version: 1.17
2019-03-08T01:16:19Z [INFO] Unable to get Docker client for version 1.18: version detection using MinAPIVersion: unsupported version: 1.18
2019-03-08T01:16:19Z [INFO] Unable to get Docker client for version 1.19: version detection using MinAPIVersion: unsupported version: 1.19
2019-03-08T01:16:19Z [INFO] Unable to get Docker client for version 1.20: version detection using MinAPIVersion: unsupported version: 1.20
2019-03-08T01:16:19Z [INFO] Unable to get Docker client for version 1.21: version detection using MinAPIVersion: unsupported version: 1.21
2019-03-08T01:16:19Z [INFO] Unable to get Docker client for version 1.22: version detection using MinAPIVersion: unsupported version: 1.22
2019-03-08T01:16:19Z [INFO] Unable to get Docker client for version 1.23: version detection using MinAPIVersion: unsupported version: 1.23
2019-03-08T01:16:19Z [INFO] Unable to get Docker client for version 1.31: version detection using MinAPIVersion: unsupported version: 1.31
2019-03-08T01:16:19Z [INFO] Unable to get Docker client for version 1.32: version detection using MinAPIVersion: unsupported version: 1.32
2019-03-08T01:16:19Z [INFO] Managed task [testShutdownOrder]: unable to create task state change event []: create task state change event api: status not recognized by ECS: NONE
2019-03-08T01:16:19Z [INFO] Task engine [testShutdownOrder]: found cached image microsoft/windowsservercore, use it directly for container C
2019-03-08T01:16:19Z [INFO] Adding image name- microsoft/windowsservercore to Image state- sha256:1fbef5019583cc35cbbe6a350b69f0b615fd2834d628ffeefef2f9f51e01a607
2019-03-08T01:16:19Z [INFO] Updating container reference C in Image State - sha256:1fbef5019583cc35cbbe6a350b69f0b615fd2834d628ffeefef2f9f51e01a607
2019-03-08T01:16:19Z [WARN] Managed task [testShutdownOrder]: failed to write container [C] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:19Z [INFO] Task engine [testShutdownOrder]: creating container: C
2019-03-08T01:16:19Z [WARN] Task testShutdownOrder container C memory setting is too low, increasing to 268435456 bytes
2019-03-08T01:16:19Z [INFO] Task engine [testShutdownOrder]: created container name mapping for task:  C -> ecs-family-1-C-dcfcb2cf85f7d2c6a701
2019-03-08T01:16:19Z [INFO] Task engine [testShutdownOrder]: created docker container for task: C -> 7a52372dc0661a1b400113e33ddf2d3a6d2785ecf7edc04e86ae3f2d93c6e329
2019-03-08T01:16:19Z [INFO] Task engine [testShutdownOrder]: created docker container for task: C -> 7a52372dc0661a1b400113e33ddf2d3a6d2785ecf7edc04e86ae3f2d93c6e329, took 19.5202ms
2019-03-08T01:16:19Z [WARN] Managed task [testShutdownOrder]: failed to write container [C] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:19Z [INFO] Task engine [testShutdownOrder]: starting container: C
2019-03-08T01:16:23Z [INFO] Task engine [testShutdownOrder]: started docker container for task: C -> 7a52372dc0661a1b400113e33ddf2d3a6d2785ecf7edc04e86ae3f2d93c6e329, took 3.1258983s
2019-03-08T01:16:23Z [WARN] Managed task [testShutdownOrder]: failed to write container [C] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:23Z [INFO] Managed task [testShutdownOrder]: sending container change event [C]: testShutdownOrder C -> RUNNING, Known Sent: NONE
2019-03-08T01:16:23Z [INFO] Managed task [testShutdownOrder]: sent container change event [C]: testShutdownOrder C -> RUNNING, Known Sent: NONE
2019-03-08T01:16:23Z [INFO] Managed task [testShutdownOrder]: redundant container state change. C to RUNNING, but already RUNNING
2019-03-08T01:16:23Z [INFO] Task engine [testShutdownOrder]: found cached image microsoft/windowsservercore, use it directly for container B
2019-03-08T01:16:23Z [INFO] Updating container reference B in Image State - sha256:1fbef5019583cc35cbbe6a350b69f0b615fd2834d628ffeefef2f9f51e01a607
2019-03-08T01:16:23Z [WARN] Managed task [testShutdownOrder]: failed to write container [B] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:23Z [INFO] Task engine [testShutdownOrder]: creating container: B
2019-03-08T01:16:23Z [WARN] Task testShutdownOrder container B memory setting is too low, increasing to 268435456 bytes
2019-03-08T01:16:23Z [INFO] Task engine [testShutdownOrder]: created container name mapping for task:  B -> ecs-family-1-B-fe8a908adaea8ec2b701
2019-03-08T01:16:23Z [INFO] Task engine [testShutdownOrder]: created docker container for task: B -> daf91503ac66de49629ff1463f57e74aa3f3d07f9819615189d76c1b7cef5c4b
2019-03-08T01:16:23Z [INFO] Task engine [testShutdownOrder]: created docker container for task: B -> daf91503ac66de49629ff1463f57e74aa3f3d07f9819615189d76c1b7cef5c4b, took 27.3455ms
2019-03-08T01:16:23Z [WARN] Managed task [testShutdownOrder]: failed to write container [B] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:23Z [INFO] Task engine [testShutdownOrder]: starting container: B
2019-03-08T01:16:25Z [INFO] Task engine [testShutdownOrder]: started docker container for task: B -> daf91503ac66de49629ff1463f57e74aa3f3d07f9819615189d76c1b7cef5c4b, took 1.9657666s
2019-03-08T01:16:25Z [WARN] Managed task [testShutdownOrder]: failed to write container [B] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:25Z [INFO] Managed task [testShutdownOrder]: sending container change event [B]: testShutdownOrder B -> RUNNING, Known Sent: NONE
2019-03-08T01:16:25Z [INFO] Managed task [testShutdownOrder]: sent container change event [B]: testShutdownOrder B -> RUNNING, Known Sent: NONE
2019-03-08T01:16:25Z [INFO] Managed task [testShutdownOrder]: redundant container state change. B to RUNNING, but already RUNNING
2019-03-08T01:16:25Z [INFO] Task engine [testShutdownOrder]: found cached image microsoft/windowsservercore, use it directly for container A
2019-03-08T01:16:25Z [INFO] Updating container reference A in Image State - sha256:1fbef5019583cc35cbbe6a350b69f0b615fd2834d628ffeefef2f9f51e01a607
2019-03-08T01:16:25Z [WARN] Managed task [testShutdownOrder]: failed to write container [A] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:25Z [INFO] Task engine [testShutdownOrder]: creating container: A
2019-03-08T01:16:25Z [WARN] Task testShutdownOrder container A memory setting is too low, increasing to 268435456 bytes
2019-03-08T01:16:25Z [INFO] Task engine [testShutdownOrder]: created container name mapping for task:  A -> ecs-family-1-A-d2eebd8a90d7aae53900
2019-03-08T01:16:25Z [INFO] Task engine [testShutdownOrder]: created docker container for task: A -> a57081700e465e60ebbd3ef1bc3204deac1b505fcc0c2ef6b849cc8446d11d80
2019-03-08T01:16:25Z [INFO] Task engine [testShutdownOrder]: created docker container for task: A -> a57081700e465e60ebbd3ef1bc3204deac1b505fcc0c2ef6b849cc8446d11d80, took 33.2086ms
2019-03-08T01:16:25Z [WARN] Managed task [testShutdownOrder]: failed to write container [A] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:25Z [INFO] Task engine [testShutdownOrder]: starting container: A
2019-03-08T01:16:29Z [INFO] Task engine [testShutdownOrder]: started docker container for task: A -> a57081700e465e60ebbd3ef1bc3204deac1b505fcc0c2ef6b849cc8446d11d80, took 4.3983237s
2019-03-08T01:16:29Z [WARN] Managed task [testShutdownOrder]: failed to write container [A] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:29Z [INFO] Managed task [testShutdownOrder]: sending container change event [A]: testShutdownOrder A -> RUNNING, Known Sent: NONE
2019-03-08T01:16:29Z [INFO] Managed task [testShutdownOrder]: sent container change event [A]: testShutdownOrder A -> RUNNING, Known Sent: NONE
2019-03-08T01:16:29Z [INFO] Managed task [testShutdownOrder]: redundant container state change. A to RUNNING, but already RUNNING
2019-03-08T01:16:29Z [INFO] Task engine [testShutdownOrder]: found cached image microsoft/windowsservercore, use it directly for container parent
2019-03-08T01:16:29Z [INFO] Updating container reference parent in Image State - sha256:1fbef5019583cc35cbbe6a350b69f0b615fd2834d628ffeefef2f9f51e01a607
2019-03-08T01:16:29Z [WARN] Managed task [testShutdownOrder]: failed to write container [parent] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:29Z [INFO] Task engine [testShutdownOrder]: creating container: parent
2019-03-08T01:16:29Z [WARN] Task testShutdownOrder container parent memory setting is too low, increasing to 268435456 bytes
2019-03-08T01:16:29Z [INFO] Task engine [testShutdownOrder]: created container name mapping for task:  parent -> ecs-family-1-parent-a0d1c1f9f9e3c498a801
2019-03-08T01:16:29Z [INFO] Task engine [testShutdownOrder]: created docker container for task: parent -> b8ed239e5294c9177f1be41642a24d069b63e4c9d5a81b1fc8b56158d6485947
2019-03-08T01:16:29Z [INFO] Task engine [testShutdownOrder]: created docker container for task: parent -> b8ed239e5294c9177f1be41642a24d069b63e4c9d5a81b1fc8b56158d6485947, took 22.4593ms
2019-03-08T01:16:29Z [WARN] Managed task [testShutdownOrder]: failed to write container [parent] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:29Z [INFO] Managed task [testShutdownOrder]: unable to create task state change event []: create task state change event api: status not recognized by ECS: CREATED
2019-03-08T01:16:29Z [INFO] Task engine [testShutdownOrder]: starting container: parent
2019-03-08T01:16:33Z [INFO] Task engine [testShutdownOrder]: started docker container for task: parent -> b8ed239e5294c9177f1be41642a24d069b63e4c9d5a81b1fc8b56158d6485947, took 4.0985045s
2019-03-08T01:16:33Z [WARN] Managed task [testShutdownOrder]: failed to write container [parent] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:33Z [INFO] Managed task [testShutdownOrder]: sending container change event [parent]: testShutdownOrder parent -> RUNNING, Known Sent: NONE
2019-03-08T01:16:33Z [INFO] Managed task [testShutdownOrder]: sent container change event [parent]: testShutdownOrder parent -> RUNNING, Known Sent: NONE
2019-03-08T01:16:33Z [INFO] Managed task [testShutdownOrder]: sending task change event [testShutdownOrder -> RUNNING, Known Sent: NONE, PullStartedAt: 0001-01-01 00:00:00 +0000 UTC, PullStoppedAt: 0001-01-01 00:00:00 +0000 UTC, ExecutionStoppedAt: 0001-01-01 00:00:00 +0000 UTC]
2019-03-08T01:16:33Z [INFO] Managed task [testShutdownOrder]: sent task change event [testShutdownOrder -> RUNNING, Known Sent: NONE, PullStartedAt: 0001-01-01 00:00:00 +0000 UTC, PullStoppedAt: 0001-01-01 00:00:00 +0000 UTC, ExecutionStoppedAt: 0001-01-01 00:00:00 +0000 UTC]
2019-03-08T01:16:33Z [INFO] Managed task [testShutdownOrder]: task at steady state: RUNNING
2019-03-08T01:16:33Z [INFO] Managed task [testShutdownOrder]: redundant container state change. parent to RUNNING, but already RUNNING
2019-03-08T01:16:33Z [INFO] Managed task [testShutdownOrder]: task at steady state: RUNNING
2019-03-08T01:16:39Z [INFO] Task [testShutdownOrder]: recording execution stopped time. Essential container [parent] stopped at: 2019-03-08 01:16:39.9535716 +0000 GMT m=+688.132778001
2019-03-08T01:16:39Z [WARN] Managed task [testShutdownOrder]: failed to write container [parent] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:39Z [INFO] Managed task [testShutdownOrder]: sending container change event [parent]: testShutdownOrder parent -> STOPPED, Exit 0, , Known Sent: NONE
2019-03-08T01:16:39Z [INFO] Managed task [testShutdownOrder]: sent container change event [parent]: testShutdownOrder parent -> STOPPED, Exit 0, , Known Sent: NONE
2019-03-08T01:16:39Z [INFO] Task engine [testShutdownOrder]: stopping container [A]
2019-03-08T01:16:40Z [WARN] Managed task [testShutdownOrder]: failed to write container [A] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:40Z [INFO] Managed task [testShutdownOrder]: sending container change event [A]: testShutdownOrder A -> STOPPED, Exit 1073807364, , Known Sent: NONE
2019-03-08T01:16:40Z [INFO] Managed task [testShutdownOrder]: sent container change event [A]: testShutdownOrder A -> STOPPED, Exit 1073807364, , Known Sent: NONE
2019-03-08T01:16:40Z [INFO] Task engine [testShutdownOrder]: stopping container [B]
2019-03-08T01:16:40Z [INFO] Managed task [testShutdownOrder]: redundant container state change. A to STOPPED, but already STOPPED
2019-03-08T01:16:40Z [INFO] Managed task [testShutdownOrder]: redundant container state change. A to STOPPED, but already STOPPED
2019-03-08T01:16:40Z [WARN] Managed task [testShutdownOrder]: failed to write container [B] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:40Z [INFO] Managed task [testShutdownOrder]: sending container change event [B]: testShutdownOrder B -> STOPPED, Exit 1073807364, , Known Sent: NONE
2019-03-08T01:16:40Z [INFO] Managed task [testShutdownOrder]: sent container change event [B]: testShutdownOrder B -> STOPPED, Exit 1073807364, , Known Sent: NONE
2019-03-08T01:16:40Z [INFO] Task engine [testShutdownOrder]: stopping container [C]
2019-03-08T01:16:40Z [INFO] Managed task [testShutdownOrder]: redundant container state change. B to STOPPED, but already STOPPED
2019-03-08T01:16:40Z [INFO] Managed task [testShutdownOrder]: redundant container state change. B to STOPPED, but already STOPPED
2019-03-08T01:16:41Z [WARN] Managed task [testShutdownOrder]: failed to write container [C] change event to tcs event stream: Event stream is closed
2019-03-08T01:16:41Z [INFO] Managed task [testShutdownOrder]: sending container change event [C]: testShutdownOrder C -> STOPPED, Exit 1073807364, , Known Sent: NONE
2019-03-08T01:16:41Z [INFO] Managed task [testShutdownOrder]: sent container change event [C]: testShutdownOrder C -> STOPPED, Exit 1073807364, , Known Sent: NONE
2019-03-08T01:16:41Z [INFO] Managed task [testShutdownOrder]: sending task change event [testShutdownOrder -> STOPPED, Known Sent: NONE, PullStartedAt: 0001-01-01 00:00:00 +0000 UTC, PullStoppedAt: 0001-01-01 00:00:00 +0000 UTC, ExecutionStoppedAt: 2019-03-08 01:16:39.9535716 +0000 GMT m=+688.132778001]
panic: test timed out after 35m0s
```

**Comment by fenxiong** [comment]
Also on linux:
```
=== RUN   TestShutdownOrder
2019-03-09T00:12:10Z [WARN] DockerGoClient: no container healthcheck data returned by Docker
2019-03-09T00:12:10Z [INFO] Image excluded from cleanup: amazon/amazon-ecs-agent:latest
2019-03-09T00:12:10Z [INFO] Image excluded from cleanup: amazon/amazon-ecs-pause:0.1.0
2019-03-09T00:12:10Z [WARN] Unable to fetch user data: blackholed
2019-03-09T00:12:10Z [CRITICAL] Unable to communicate with EC2 Metadata service to infer region: blackholed
2019-03-09T00:12:10Z [CRITICAL] Configuration key not set, key: AWSRegion
2019-03-09T00:12:10Z [INFO] Managed task [testShutdownOrder]: unable to create task state change event []: create task state change event api: status not recognized by ECS: NONE
2019-03-09T00:12:10Z [INFO] Task engine [testShutdownOrder]: found cached image 127.0.0.1:51670/busybox, use it directly for container C
2019-03-09T00:12:10Z [INFO] Adding image name- 127.0.0.1:51670/busybox to Image state- sha256:758ec7f3a1ee85f8f08399b55641bfb13e8c1109287ddc5e22b68c3d653152ee
2019-03-09T00:12:10Z [INFO] Updating container reference C in Image State - sha256:758ec7f3a1ee85f8f08399b55641bfb13e8c1109287ddc5e22b68c3d653152ee
2019-03-09T00:12:10Z [WARN] Managed task [testShutdownOrder]: failed to write container [C] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:10Z [INFO] Task engine [testShutdownOrder]: creating container: C
2019-03-09T00:12:10Z [INFO] Task engine [testShutdownOrder]: created container name mapping for task:  C -> ecs-family-1-C-88ccc9a8b294dcb44500
2019-03-09T00:12:10Z [INFO] Task engine [testShutdownOrder]: created docker container for task: C -> 2a524ef338b13cbb5590cf7757c106d6a9c5dde1c6e65b5718aa879521635f9f
2019-03-09T00:12:10Z [INFO] Task engine [testShutdownOrder]: created docker container for task: C -> 2a524ef338b13cbb5590cf7757c106d6a9c5dde1c6e65b5718aa879521635f9f, took 244.134341ms
2019-03-09T00:12:10Z [WARN] Managed task [testShutdownOrder]: failed to write container [C] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:10Z [INFO] Task engine [testShutdownOrder]: starting container: C
2019-03-09T00:12:11Z [INFO] Task engine [testShutdownOrder]: started docker container for task: C -> 2a524ef338b13cbb5590cf7757c106d6a9c5dde1c6e65b5718aa879521635f9f, took 312.568247ms
2019-03-09T00:12:11Z [WARN] Managed task [testShutdownOrder]: failed to write container [C] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:11Z [INFO] Managed task [testShutdownOrder]: sending container change event [C]: testShutdownOrder C -> RUNNING, Known Sent: NONE
2019-03-09T00:12:11Z [INFO] Managed task [testShutdownOrder]: sent container change event [C]: testShutdownOrder C -> RUNNING, Known Sent: NONE
2019-03-09T00:12:11Z [INFO] Managed task [testShutdownOrder]: redundant container state change. C to RUNNING, but already RUNNING
2019-03-09T00:12:11Z [INFO] Task engine [testShutdownOrder]: found cached image 127.0.0.1:51670/busybox, use it directly for container B
2019-03-09T00:12:11Z [INFO] Updating container reference B in Image State - sha256:758ec7f3a1ee85f8f08399b55641bfb13e8c1109287ddc5e22b68c3d653152ee
2019-03-09T00:12:11Z [WARN] Managed task [testShutdownOrder]: failed to write container [B] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:11Z [INFO] Task engine [testShutdownOrder]: creating container: B
2019-03-09T00:12:11Z [INFO] Task engine [testShutdownOrder]: created container name mapping for task:  B -> ecs-family-1-B-a09ea58ca595edf9de01
2019-03-09T00:12:11Z [INFO] Task engine [testShutdownOrder]: created docker container for task: B -> f9f8a87830b58a0e8b64188aec3c53875b5a1f675ff33d313da027241ad65910
2019-03-09T00:12:11Z [INFO] Task engine [testShutdownOrder]: created docker container for task: B -> f9f8a87830b58a0e8b64188aec3c53875b5a1f675ff33d313da027241ad65910, took 228.802888ms
2019-03-09T00:12:11Z [WARN] Managed task [testShutdownOrder]: failed to write container [B] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:11Z [INFO] Task engine [testShutdownOrder]: starting container: B
2019-03-09T00:12:11Z [INFO] Task engine [testShutdownOrder]: started docker container for task: B -> f9f8a87830b58a0e8b64188aec3c53875b5a1f675ff33d313da027241ad65910, took 421.166195ms
2019-03-09T00:12:11Z [WARN] Managed task [testShutdownOrder]: failed to write container [B] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:11Z [INFO] Managed task [testShutdownOrder]: sending container change event [B]: testShutdownOrder B -> RUNNING, Known Sent: NONE
2019-03-09T00:12:11Z [INFO] Managed task [testShutdownOrder]: sent container change event [B]: testShutdownOrder B -> RUNNING, Known Sent: NONE
2019-03-09T00:12:11Z [INFO] Managed task [testShutdownOrder]: redundant container state change. B to RUNNING, but already RUNNING
2019-03-09T00:12:11Z [INFO] Task engine [testShutdownOrder]: found cached image 127.0.0.1:51670/busybox, use it directly for container A
2019-03-09T00:12:11Z [INFO] Updating container reference A in Image State - sha256:758ec7f3a1ee85f8f08399b55641bfb13e8c1109287ddc5e22b68c3d653152ee
2019-03-09T00:12:11Z [WARN] Managed task [testShutdownOrder]: failed to write container [A] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:11Z [INFO] Task engine [testShutdownOrder]: creating container: A
2019-03-09T00:12:11Z [INFO] Task engine [testShutdownOrder]: created container name mapping for task:  A -> ecs-family-1-A-c6d3a78ea0bf97dd5600
2019-03-09T00:12:12Z [INFO] Task engine [testShutdownOrder]: created docker container for task: A -> 618ba189b3d5460c25ea880c90ea1850f72747ebe9028677cd09f423851f1a09
2019-03-09T00:12:12Z [INFO] Task engine [testShutdownOrder]: created docker container for task: A -> 618ba189b3d5460c25ea880c90ea1850f72747ebe9028677cd09f423851f1a09, took 269.620411ms
2019-03-09T00:12:12Z [WARN] Managed task [testShutdownOrder]: failed to write container [A] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:12Z [INFO] Task engine [testShutdownOrder]: starting container: A
2019-03-09T00:12:12Z [WARN] Managed task [testShutdownOrder]: failed to write container [A] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:12Z [INFO] Managed task [testShutdownOrder]: sending container change event [A]: testShutdownOrder A -> RUNNING, Known Sent: NONE
2019-03-09T00:12:12Z [INFO] Managed task [testShutdownOrder]: sent container change event [A]: testShutdownOrder A -> RUNNING, Known Sent: NONE
2019-03-09T00:12:12Z [INFO] Task engine [testShutdownOrder]: started docker container for task: A -> 618ba189b3d5460c25ea880c90ea1850f72747ebe9028677cd09f423851f1a09, took 293.478596ms
2019-03-09T00:12:12Z [INFO] Managed task [testShutdownOrder]: redundant container state change. A to RUNNING, but already RUNNING
2019-03-09T00:12:12Z [INFO] Task engine [testShutdownOrder]: found cached image 127.0.0.1:51670/busybox, use it directly for container parent
2019-03-09T00:12:12Z [INFO] Updating container reference parent in Image State - sha256:758ec7f3a1ee85f8f08399b55641bfb13e8c1109287ddc5e22b68c3d653152ee
2019-03-09T00:12:12Z [WARN] Managed task [testShutdownOrder]: failed to write container [parent] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:12Z [INFO] Task engine [testShutdownOrder]: creating container: parent
2019-03-09T00:12:12Z [INFO] Task engine [testShutdownOrder]: created container name mapping for task:  parent -> ecs-family-1-parent-8ee7ddab8fc5a4cbb401
2019-03-09T00:12:12Z [INFO] Task engine [testShutdownOrder]: created docker container for task: parent -> 8ff448ef6dda498504eb2a728e770b6fecb6f104787f38ca84e06e76c5427abc
2019-03-09T00:12:12Z [INFO] Task engine [testShutdownOrder]: created docker container for task: parent -> 8ff448ef6dda498504eb2a728e770b6fecb6f104787f38ca84e06e76c5427abc, took 238.464356ms
2019-03-09T00:12:12Z [WARN] Managed task [testShutdownOrder]: failed to write container [parent] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:12Z [INFO] Managed task [testShutdownOrder]: unable to create task state change event []: create task state change event api: status not recognized by ECS: CREATED
2019-03-09T00:12:12Z [INFO] Task engine [testShutdownOrder]: starting container: parent
2019-03-09T00:12:12Z [WARN] Managed task [testShutdownOrder]: failed to write container [parent] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:12Z [INFO] Managed task [testShutdownOrder]: sending container change event [parent]: testShutdownOrder parent -> RUNNING, Known Sent: NONE
2019-03-09T00:12:12Z [INFO] Managed task [testShutdownOrder]: sent container change event [parent]: testShutdownOrder parent -> RUNNING, Known Sent: NONE
2019-03-09T00:12:12Z [INFO] Task engine [testShutdownOrder]: started docker container for task: parent -> 8ff448ef6dda498504eb2a728e770b6fecb6f104787f38ca84e06e76c5427abc, took 317.710236ms
2019-03-09T00:12:12Z [INFO] Managed task [testShutdownOrder]: sending task change event [testShutdownOrder -> RUNNING, Known Sent: NONE, PullStartedAt: 0001-01-01 00:00:00 +0000 UTC, PullStoppedAt: 0001-01-01 00:00:00 +0000 UTC, ExecutionStoppedAt: 0001-01-01 00:00:00 +0000 UTC]
2019-03-09T00:12:12Z [INFO] Managed task [testShutdownOrder]: sent task change event [testShutdownOrder -> RUNNING, Known Sent: NONE, PullStartedAt: 0001-01-01 00:00:00 +0000 UTC, PullStoppedAt: 0001-01-01 00:00:00 +0000 UTC, ExecutionStoppedAt: 0001-01-01 00:00:00 +0000 UTC]
2019-03-09T00:12:12Z [INFO] Managed task [testShutdownOrder]: task at steady state: RUNNING
2019-03-09T00:12:12Z [INFO] Managed task [testShutdownOrder]: redundant container state change. parent to RUNNING, but already RUNNING
2019-03-09T00:12:12Z [INFO] Managed task [testShutdownOrder]: task at steady state: RUNNING
2019-03-09T00:12:13Z [INFO] Task [testShutdownOrder]: recording execution stopped time. Essential container [parent] stopped at: 2019-03-09 00:12:13.221406815 +0000 UTC m=+397.790763793
2019-03-09T00:12:13Z [WARN] Managed task [testShutdownOrder]: failed to write container [parent] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:13Z [INFO] Managed task [testShutdownOrder]: sending container change event [parent]: testShutdownOrder parent -> STOPPED, Exit 0, , Known Sent: NONE
2019-03-09T00:12:13Z [INFO] Managed task [testShutdownOrder]: sent container change event [parent]: testShutdownOrder parent -> STOPPED, Exit 0, , Known Sent: NONE
2019-03-09T00:12:13Z [INFO] Task engine [testShutdownOrder]: stopping container [A]
2019-03-09T00:12:43Z [WARN] Managed task [testShutdownOrder]: failed to write container [A] change event to tcs event stream: Event stream is closed
2019-03-09T00:12:43Z [INFO] Managed task [testShutdownOrder]: sending container change event [A]: testShutdownOrder A -> STOPPED, Exit 137, , Known Sent: NONE
2019-03-09T00:12:43Z [INFO] Managed task [testShutdownOrder]: sent container change event [A]: testShutdownOrder A -> STOPPED, Exit 137, , Known Sent: NONE
2019-03-09T00:12:43Z [INFO] Managed task [testShutdownOrder]: redundant container state change. A to STOPPED, but already STOPPED
2019-03-09T00:12:43Z [INFO] Task engine [testShutdownOrder]: stopping container [B]
2019-03-09T00:12:43Z [INFO] Managed task [testShutdownOrder]: redundant container state change. A to STOPPED, but already STOPPED
2019-03-09T00:13:13Z [WARN] Managed task [testShutdownOrder]: failed to write container [B] change event to tcs event stream: Event stream is closed
2019-03-09T00:13:13Z [INFO] Managed task [testShutdownOrder]: sending container change event [B]: testShutdownOrder B -> STOPPED, Exit 137, , Known Sent: NONE
2019-03-09T00:13:13Z [INFO] Managed task [testShutdownOrder]: sent container change event [B]: testShutdownOrder B -> STOPPED, Exit 137, , Known Sent: NONE
2019-03-09T00:13:13Z [INFO] Managed task [testShutdownOrder]: redundant container state change. B to STOPPED, but already STOPPED
2019-03-09T00:13:13Z [INFO] Task engine [testShutdownOrder]: stopping container [C]
2019-03-09T00:13:13Z [INFO] Managed task [testShutdownOrder]: redundant container state change. B to STOPPED, but already STOPPED
2019-03-09T00:13:44Z [WARN] Managed task [testShutdownOrder]: failed to write container [C] change event to tcs event stream: Event stream is closed
2019-03-09T00:13:44Z [INFO] Managed task [testShutdownOrder]: sending container change event [C]: testShutdownOrder C -> STOPPED, Exit 137, , Known Sent: NONE
2019-03-09T00:13:44Z [INFO] Managed task [testShutdownOrder]: sent container change event [C]: testShutdownOrder C -> STOPPED, Exit 137, , Known Sent: NONE
2019-03-09T00:13:44Z [INFO] Managed task [testShutdownOrder]: sending task change event [testShutdownOrder -> STOPPED, Known Sent: NONE, PullStartedAt: 0001-01-01 00:00:00 +0000 UTC, PullStoppedAt: 0001-01-01 00:00:00 +0000 UTC, ExecutionStoppedAt: 2019-03-09 00:12:13.221406815 +0000 UTC m=+397.790763793]
panic: test timed out after 20m0s
```

**Comment by fenxiong** [comment]
There is a deadlock between the following two goroutines at the end of the test (the former one holds the lock):

```
goroutine 2673 [chan send, 28 minutes]:
github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).emitDockerContainerChange(0xc0008725b0, 0xc0007598c0, 0x5, 0xc00001d580, 0x40, 0xc000d04ec0, 0x15ead08, 0x0, 0x0, 0x0, ...)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/engine/task_manager.go:531 +0xdc
github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).handleDockerEvent(0xc0005137a0, 0x5, 0xc00001d580, 0x40, 0xc000d04ec0, 0x15ead08, 0x0, 0x0, 0x0, 0x0, ...)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/engine/docker_task_engine.go:608 +0xa10
github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).handleDockerEvents(0xc0005137a0, 0x10383a0, 0xc0004c9440)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/engine/docker_task_engine.go:560 +0xf3
created by github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).Init
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/engine/docker_task_engine.go:218 +0x170


goroutine 2693 [semacquire, 28 minutes]:
sync.runtime_SemacquireMutex(0xc000513840, 0x0)
	c:/go/src/runtime/sema.go:71 +0x44
sync.(*RWMutex).Lock(0xc000513838)
	c:/go/src/sync/rwmutex.go:98 +0xe6
github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).Disable(0xc0005137a0)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/engine/docker_task_engine.go:262 +0x48
github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).Shutdown(0xc0005137a0)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/engine/docker_task_engine.go:257 +0x68
github.com/aws/amazon-ecs-agent/agent/engine.setup.func1()
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/engine/common_integ_test.go:100 +0x49
github.com/aws/amazon-ecs-agent/agent/engine.TestShutdownOrder(0xc000798400)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/engine/ordering_integ_test.go:433 +0x12f0
testing.tRunner(0xc000798400, 0xee4d98)
	c:/go/src/testing/testing.go:827 +0x16a
created by testing.(*T).Run
	c:/go/src/testing/testing.go:878 +0x658
```

**Comment by fenxiong** [comment]
fixed in https://github.com/aws/amazon-ecs-agent/pull/2014, closing.
