### ISSUE TITLE
TestConnectionIsClosedOnIdle timed out occasionally in travis osx build

### ISSUE THREAD

**Issue by fenxiong** [aws/amazon-ecs-agent#2130]
### Summary

TestConnectionIsClosedOnIdle timed out in travis osx build in several recent PR.

### Description

```
=== RUN   TestConnectionIsClosedOnIdle
2019-07-11T23:17:49Z [INFO] ACS session context cancelled.
2019-07-11T23:17:49Z [INFO] Reconnecting to ACS in: 440.05002ms
2019-07-11T23:17:49Z [INFO] Interrupted waiting for reconnect delay to elapse; Expect session to close
2019-07-11T23:17:49Z [INFO] Connected to ACS endpoint
2019-07-11T23:17:49Z [INFO] ACS connection closed: EOF
coverage: 36.0% of statements
panic: test timed out after 30s
goroutine 328 [running]:
testing.(*M).startAlarm.func1()
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/testing/testing.go:1334 +0x11c
created by time.goFunc
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/time/sleep.go:169 +0x52
goroutine 1 [chan receive]:
testing.(*T).Run(0xc000185300, 0x1abbf20, 0x1c, 0x1ad9468, 0x1)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/testing/testing.go:917 +0x6d2
testing.runTests.func1(0xc000185300)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/testing/testing.go:1157 +0xa9
testing.tRunner(0xc000185300, 0xc00024bd48)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/testing/testing.go:865 +0x164
testing.runTests(0xc000372620, 0x222ff40, 0x45, 0x45, 0x0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/testing/testing.go:1155 +0x524
testing.(*M).Run(0xc000392000, 0x0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/testing/testing.go:1072 +0x2ec
main.main()
	_testmain.go:238 +0x335
goroutine 19 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/proc.go:307
sync.runtime_notifyListWait(0xc00008b450, 0x0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/sema.go:510 +0xf9
sync.(*Cond).Wait(0xc00008b440)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/sync/cond.go:56 +0x8e
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc000180cf0, 0x0)
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x101
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc000180cf0)
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x50
created by github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.NewAsyncLoopLogger
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0xdd
goroutine 20 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/proc.go:307
sync.runtime_notifyListWait(0xc00008b5d0, 0x0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/sema.go:510 +0xf9
sync.(*Cond).Wait(0xc00008b5c0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/sync/cond.go:56 +0x8e
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc000180e10, 0x0)
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x101
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc000180e10)
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x50
created by github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.NewAsyncLoopLogger
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0xdd
goroutine 21 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/proc.go:307
sync.runtime_notifyListWait(0xc00008bc90, 0x48)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/sema.go:510 +0xf9
sync.(*Cond).Wait(0xc00008bc80)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/sync/cond.go:56 +0x8e
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc000180f30, 0x0)
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x101
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc000180f30)
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x50
created by github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.NewAsyncLoopLogger
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0xdd
goroutine 23 [syscall]:
os/signal.signal_recv(0x1096991)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/os/signal/signal_unix.go:23 +0x30
created by os/signal.init.0
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/os/signal/signal_unix.go:29 +0x4f
goroutine 160 [chan send]:
github.com/aws/amazon-ecs-agent/agent/acs/handler.sendEmptyMessageOnChannel.func1(0xc0003ec5a0)
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/acs/handler/acs_handler.go:482 +0x5b
created by github.com/aws/amazon-ecs-agent/agent/acs/handler.sendEmptyMessageOnChannel
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/acs/handler/acs_handler.go:481 +0x65
goroutine 326 [sleep]:
runtime.goparkunlock(...)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/proc.go:307
time.Sleep(0x2f2a40f6f)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/time.go:105 +0x159
github.com/aws/amazon-ecs-agent/agent/utils.NewJitteredTicker.func1(0xc0004152c0, 0x1c6df00, 0xc000466180, 0x2540be400, 0x6fc23ac00)
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/utils/ticker.go:34 +0x7d
created by github.com/aws/amazon-ecs-agent/agent/utils.NewJitteredTicker
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/utils/ticker.go:26 +0x92
goroutine 269 [chan receive]:
github.com/aws/amazon-ecs-agent/agent/acs/handler.TestConnectionIsClosedOnIdle(0xc0003a8a00)
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/acs/handler/acs_handler_test.go:819 +0x100c
testing.tRunner(0xc0003a8a00, 0x1ad9468)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/testing/testing.go:916 +0x69a
goroutine 133 [chan send]:
github.com/aws/amazon-ecs-agent/agent/acs/handler.sendEmptyMessageOnChannel.func1(0xc0003e4000)
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/acs/handler/acs_handler.go:482 +0x5b
created by github.com/aws/amazon-ecs-agent/agent/acs/handler.sendEmptyMessageOnChannel
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/acs/handler/acs_handler.go:481 +0x65
goroutine 270 [select]:
github.com/aws/amazon-ecs-agent/agent/eventhandler.(*TaskHandler).startDrainEventsTicker(0xc00039ea20)
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/task_handler.go:165 +0x1f2
created by github.com/aws/amazon-ecs-agent/agent/eventhandler.NewTaskHandler
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/task_handler.go:118 +0x281
goroutine 152 [chan send]:
github.com/aws/amazon-ecs-agent/agent/acs/handler.sendEmptyMessageOnChannel.func1(0xc0003e4780)
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/acs/handler/acs_handler.go:482 +0x5b
created by github.com/aws/amazon-ecs-agent/agent/acs/handler.sendEmptyMessageOnChannel
	/Users/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/acs/handler/acs_handler.go:481 +0x65
FAIL	github.com/aws/amazon-ecs-agent/agent/acs/handler	30.130s
?   	github.com/aws/amazon-ecs-agent/agent/acs/model	[no test files]
?   	github.com/aws/amazon-ecs-agent/agent/acs/model/ecsacs	[no test files]
```

### Expected Behavior
Test passed.

### Observed Behavior
Test failed.

**Comment by fenxiong** [comment]
possibly fixed by https://github.com/aws/amazon-ecs-agent/pull/2210 and the test isn't failing anymore. closing
