### ISSUE TITLE
Deleting stopped/crashed containers outside of ECS agent breaks ECS terribly

### ISSUE THREAD

**Issue by pcarrier** [aws/amazon-ecs-agent#364]
We have been removing Docker containers periodically, which is partly useful because we run non-ECS Docker containers.

This can cause ECS to never detect that a container is no longer running.

Sanitized example of `amazon-ecs-agent` log entry:

```
Apr 05 10:34:06 ip-10-1-2-3 amazon-ecs-agent[1356]: 2016-04-05T10:34:06Z [INFO] Redundant container state change for task my-service:2 arn:aws:ecs:us-east-1:123456789:task/4111a88e-1e55-4c7f-a12b-256104b8f77a, Status: (RUNNING->RUNNING) Containers: [my-service (RUNNING->RUNNING),]: my-service(example/my-service:v42) (RUNNING->RUNNING) to NONE, but already RUNNING
```

The task shows up as running in the AWS console.

Now for the source of the bug as I understand:

The states for a container are, in increasing order:
- `ContainerStatusNone = iota`
- `ContainerPulled`
- `ContainerCreated`
- `ContainerRunning`
- `ContainerStopped`
- `ContainerZombie // Impossible status to use as a virtual 'max'`

Task management in ECS basically expects container state to increase over time (covering the `ContainerRunning`->`ContainerStopped` edge case, hence "basically"). The details are in `func (task *managedTask) overseeTask()`.

When a container is deleted before the agent sees it as stopped, it assumes it's still running forever.

**Comment by kiranmeduri** [comment]
Thank you for reporting this issue. Seems like this is a bug in agent due to race-condition. However I am unable to reproduce on my side because ecs-agent on the host where I am running is handling the stop event before getting into bad state. Here is what I did

- Start large number (100) of containers on instance using ecs.StartTask
- Once they are all running issue ```docker rm -f```
- Verified using ecs.ListTasks 

From docker logs I see

```
2016-04-07T15:21:04Z [INFO] Redundant container state change for task sleep:1 arn:aws:ecs:us-west-2:123456789:task/000000000-d920-4ab2-a74c-1111111111, Status: (STOPPED->STOPPED) Containers: [c1 (STOPPED->STOPPED),]: c1(ubuntu) (STOPPED->STOPPED) to NONE, but already STOPPED
```

Can you provide some details on what command/script you are using to clear the containers. Also helps to know if there is any pattern when this triggers or if it happens everytime. For e.g. cpu/memory consumption on the instances, etc.

Thanks again for reaching out.

-kiran

**Comment by pcarrier** [comment]
We have been running this every 10 minutes (now taken out of one prod cluster in our environment):

```
/usr/bin/docker rm -v $(/usr/bin/docker ps -a -q -f status=exited)
/usr/bin/docker rmi $(/usr/bin/docker images -f "dangling=true" -q)
```

We've seen this issue on a cluster where we run 3 ECS tasks total, and less than a dozen non-ECS, stable (don't restart often if ever) Docker containers, and the machines are nowhere near loaded. But it might be hard to reproduce as amazon-ecs-agent has to miss the initial deletion.

However we have reasonable and slowly growing evidence (from yesterday's hotfix where we stopped deleting containers, see http://status.meteor.com/incidents/6kdh090xzwxv for its production deploy) that on larger clusters (many dozens of instances, many hundreds of tasks) with a lot of task churn, dozens of containers can become RUNNING ghosts in a few days.

**Comment by aaithal** [comment]
@pcarrier A remediation in the meantime would be to let the ECS Agent cleanup the containers that it launches by setting the `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` to a value less than the default value of 3 hours (Example: `10m`). You can supplement this by running a clean-up script similar to the one that you mentioned earlier, but with a minor modification to only cleaning up those containers which are not launched by the ECS Agent, by checking for the presence of the label `com.amazonaws.ecs.task-arn` or of `com.amazonaws.ecs.container-name`:

```bash
docker ps -aq -f status=exited | grep -v $(docker ps -q -f label=com.amazonaws.ecs.task-arn -f status=exited)
```

**Comment by pcarrier** [comment]
@aaithal we implemented something along those lines :)

**Comment by samuelkarp** [comment]
@pcarrier Do you have more detailed logs from the ECS agent when this happens (especially at debug level)?  If possible, we'd like to figure out how the initial event indicating that the container exited got missed by the agent.

**Comment by pcarrier** [comment]
@samuelkarp no, sorry. We're using amazon-ecs-agent 1.8.2 and Docker 1.10.3.

**Comment by samuelkarp** [comment]
Unfortunately it's going to be fairly difficult for us to track down exactly what's causing the agent to get into this state without logs or a repro case.  We'll keep attempting to reproduce this behavior and will update here when we have more information.  Until then, the mitigation that @aaithal recommended is still the best option; you should end up with about [10 minutes](https://github.com/aws/amazon-ecs-agent/blob/v1.8.2/agent/engine/task_manager.go#L28) of inconsistency in the worst case before the agent would correctly detect that the container has stopped and continue working.

Can you share more details of your setup?  I'm particularly interested in:
* How you configure the ECS agent (usually in `/etc/ecs/ecs.config` on the ECS-optimized AMI or passed to `docker run` when you run the agent)
* How you configure the Docker daemon (usually in `/etc/sysconfig/docker` or `/etc/default/docker`)
* The output of `docker info`

**Comment by pcarrier** [comment]
I'm very confused. Do you expect to reliably receive state transitions from Docker? If you don't, is there something unclear about the problem we're running into?

**Comment by samuelkarp** [comment]
Yes, we expect to reliably receive state transitions from Docker.

**Comment by samuelkarp** [comment]
@pcarrier How long does it typically take for you to see this behavior?  I've been running a setup for several hours now attempting to reproduce this with no success; I'll leave it running the rest of the day and overnight if nothing shows.

For reference, I'm attempting to reproduce with this setup:
* An Ubuntu 14.04 EC2 instance with Docker 1.10.3 and ECS agent 1.8.2 running in its own cluster (default options for both Docker and the ECS agent)
* An ECS service with a large desired count where the task exits after 30 seconds (essentially `sleep 30`)
* A script running on the instance to clean up containers (modeled after your cron job)
* A monitoring script reporting the longest-running tasks by calling `DescribeTasks`

**Comment by pcarrier** [comment]
@samuelkarp we saw it a few times. We _might_ only see it with oom-killed tasks. We've stopped removing from Docker ourselves for now so hard to reproduce, but we're rolling out ECS_LOGLEVEL=DEBUG 100% of the time everywhere and I'll try to reproduce in dev after that.

**Comment by samuelkarp** [comment]
@pcarrier I'll adjust my test setup to have a mix of normally-exiting containers and oom-ing containers.

**Comment by samuelkarp** [comment]
@pcarrier I've been running this for a few more hours with a task that gets oom-killed and still have not seen the behavior you're reporting.  I'll let it run overnight, but at this point I'm doubtful I'll see it reproduce.  If you can share more details of your setup (same questions as [before](https://github.com/aws/amazon-ecs-agent/issues/364#issuecomment-209107597)), that would be very helpful.

**Comment by samuelkarp** [comment]
@pcarrier I haven't been able to reproduce this at all.  If you have any more information you're able to share, we would definitely appreciate it.

**Comment by pcarrier** [comment]
@samuelkarp we've been rolling out DEBUG level everywhere, but quite frankly we try to resolve sources of crashes in staging/prod so whilst I can try to reproduce in a dev env it might not be easy... I'll try to get to it ASAP.

**Comment by pcarrier** [comment]
How does ecs-agent make sure not to miss events if it loses its HTTP connection? Logs from prod:

```
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: goroutine 15903681 [running]:
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve.func1(0xc8213f0d10, 0x7f5df2aa2218, 0xc8216091a0)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1287 +0xb5
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetByName(0xc820157800, 0xc82321ca57, 0x0, 0x0, 0x0, 0x0)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:529 +0x3fb
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetContainer(0xc820157800, 0xc82321ca57, 0x0, 0x0, 0x0, 0x0)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:149 +0xd2
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).ContainerRm(0xc820157800, 0xc82321ca57, 0x0, 0xc82201eb00, 0x0, 0x0)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/delete.go:22 +0x6e
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).deleteContainers(0xc820754c60, 0x7f5df2aefb08, 0xc82321cba0, 0x7f5df2aef800, 0xc8213f0dc0, 0xc82471c620, 0xc82321cae0, 0x0, 0x0)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container_routes.go:401 +0x1de
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.deleteContainers)-fm(0x7f5df2aefb08, 0xc82321cba0, 0x7f5df2aef800, 0xc8213f0dc0
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container.go:64 +0x74
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.versionMiddleware.func1(0x7f5df2aefb08, 0xc82321cba0, 0x7f5df2aef800, 0xc8213f0dc0, 0xc82471c620, 0xc82321cae0, 0x0, 0x0)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc8213f0dc0, 0xc82471c620, 0xc82321cae0, 0x0, 0x0)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc8213f0dc0, 0xc82471c620, 0xc82321cae0, 0x0, 0x0)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5df2aef800, 0xc8213f0dc0, 0xc82471c620)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/server.go:169 +0x2ad
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: net/http.HandlerFunc.ServeHTTP(0xc8208f6740, 0x7f5df2aef800, 0xc8213f0dc0, 0xc82471c620)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1422 +0x3a
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc8207febe0, 0x7f5df2aef800, 0xc8213f0dc0, 0xc82471c620)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8209fe4d0, 0x7f5df2aef800, 0xc8213f0dc0, 0xc82471c620)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: net/http.serverHandler.ServeHTTP(0xc82016e9c0, 0x7f5df2aef800, 0xc8213f0dc0, 0xc82471c620)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1862 +0x19e
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve(0xc8213f0d10)
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1361 +0xbee
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]: created by net/http.(*Server).Serve
Apr 17 05:42:44 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by pcarrier** [comment]
(The removal cronjob hasn't made it back to any of our environments yet)

**Comment by samuelkarp** [comment]
@pcarrier There's a [steady state verification](https://github.com/aws/amazon-ecs-agent/blob/v1.8.2/agent/engine/task_manager.go#L134-L135) that happens every 10 minutes to compensate for things getting missed.

Are you still seeing problems, even when switching to `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` instead of your cron with `docker rm`?

**Comment by pcarrier** [comment]
That is, indeed, what we did, and yes. We have a case with AWS support. Would love to follow up there ,(#1719643441), but that new issue probably doesn't belong here :)

**Comment by samuelkarp** [comment]
To follow up: We've merged #390 into the `dev` branch and also believe that #395 should help, but that still needs more testing.

**Comment by aaithal** [comment]
Follow-up: We have merged #395, which should resolve this issue. Marking this as pending release.
