### ISSUE TITLE
container stopped immediately when run with ECS Task but stays run with 'docker run'

### ISSUE THREAD

**Issue by YurgenUA** [aws/amazon-ecs-agent#594]
With one of my docker image I experience a strange behavior:
- when SSH to EC2 and do 'docker run -it <image:tag>' my container runs and work OK
- wen I push ECS Task from AWS ECS Console, my tasks stays couple seconds in PENDING state and then gone. Task has status STOPPED and container has Exit Code 139.
 ecs-agent log has no errors (below is content).
Any advise on how to troubleshoot?
==============
2016-11-10T20:20:13Z [INFO] Starting Agent: Amazon ECS Agent - v1.13.0 (aebcbca)
2016-11-10T20:20:13Z [INFO] Loading configuration
2016-11-10T20:20:13Z [WARN] Invalid format for "ECS_NUM_IMAGES_DELETE_PER_CYCLE", expected an integer. err strconv.ParseInt: parsing "": invalid syntax
2016-11-10T20:20:13Z [INFO] Event stream ContainerChange start listening...
2016-11-10T20:20:13Z [INFO] Checkpointing is enabled. Attempting to load state
2016-11-10T20:20:13Z [INFO] Loading state! module="statemanager"
2016-11-10T20:20:13Z [INFO] Detected Docker versions [1.17 1.18 1.19 1.20 1.21 1.22 1.23]
2016-11-10T20:20:13Z [INFO] Registering Instance with ECS
2016-11-10T20:20:13Z [INFO] Registered! module="api client"
2016-11-10T20:20:13Z [INFO] Registration completed successfully. I am running as 'arn:aws:ecs:eu-central-1:162782911101:container-instance/18fcd190-95a8-4018-9549-4590eff49456' in cluster 'default'
2016-11-10T20:20:13Z [INFO] Saving state! module="statemanager"
2016-11-10T20:20:13Z [INFO] Beginning Polling for updates
2016-11-10T20:20:13Z [INFO] Event stream DeregisterContainerInstance start listening...
2016-11-10T20:20:13Z [INFO] Initializing stats engine
2016-11-10T20:20:13Z [INFO] Creating poll dialer, host: ecs-a-1.eu-central-1.amazonaws.com
2016-11-10T20:20:13Z [INFO] Creating poll dialer, host: ecs-t-1.eu-central-1.amazonaws.com
2016-11-10T20:20:23Z [INFO] Saving state! module="statemanager"
2016-11-10T20:23:31Z [INFO] Saving state! module="statemanager"
2016-11-10T20:23:31Z [INFO] Pulling container module="TaskEngine" task="task_def:1 arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa, Status: (NONE->RUNNING) Containers: [cont_def (NONE->RUNNING),]" container="cont_def(162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master) (NONE->RUNNING)"
2016-11-10T20:24:03Z [INFO] Adding image name- 162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master to Image state- sha256:9b90ff41179f2a073529ddc4659605b69d2d8cf80f07f5f9ac76a98371cbd1ce
2016-11-10T20:24:03Z [INFO] Updating container reference cont_def in Image State - sha256:9b90ff41179f2a073529ddc4659605b69d2d8cf80f07f5f9ac76a98371cbd1ce
2016-11-10T20:24:03Z [INFO] Saving state! module="statemanager"
2016-11-10T20:24:03Z [INFO] Creating container module="TaskEngine" task="task_def:1 arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa, Status: (NONE->RUNNING) Containers: [cont_def (PULLED->RUNNING),]" container="cont_def(162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master) (PULLED->RUNNING)"
2016-11-10T20:24:03Z [INFO] Created container name mapping for task task_def:1 arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa, Status: (NONE->RUNNING) Containers: [cont_def (PULLED->RUNNING),] - cont_def(162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master) (PULLED->RUNNING) -> ecs-task_def-1-contdef-c8d6acf9a9b8bdc59e01
2016-11-10T20:24:03Z [INFO] Saving state! module="statemanager"
2016-11-10T20:24:03Z [INFO] Created docker container for task task_def:1 arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa, Status: (CREATED->RUNNING) Containers: [cont_def (CREATED->RUNNING),]: cont_def(162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master) (CREATED->RUNNING) -> be6256dc8dffaf209d165f7e9371a82affbfcbfe81676257000b46775633b077
2016-11-10T20:24:03Z [INFO] Starting container module="TaskEngine" task="task_def:1 arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa, Status: (CREATED->RUNNING) Containers: [cont_def (CREATED->RUNNING),]" container="cont_def(162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master) (CREATED->RUNNING)"
2016-11-10T20:24:03Z [INFO] Redundant container state change for task task_def:1 arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa, Status: (CREATED->RUNNING) Containers: [cont_def (CREATED->RUNNING),]: cont_def(162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master) (CREATED->RUNNING) to CREATED, but already CREATED
2016-11-10T20:24:04Z [INFO] Task change event module="TaskEngine" event="{TaskArn:arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa Status:RUNNING Reason: SentStatus:NONE}"
2016-11-10T20:24:04Z [INFO] Adding event module="eventhandler" change="ContainerChange: arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa cont_def -> RUNNING, Known Sent: NONE"
2016-11-10T20:24:04Z [INFO] Adding event module="eventhandler" change="TaskChange: arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa -> RUNNING, Known Sent: NONE"
2016-11-10T20:24:04Z [INFO] Sending container change module="eventhandler" event="ContainerChange: arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa cont_def -> RUNNING, Known Sent: NONE" change="ContainerChange: arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa cont_def -> RUNNING, Known Sent: NONE"
2016-11-10T20:24:04Z [INFO] Redundant container state change for task task_def:1 arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa, Status: (RUNNING->RUNNING) Containers: [cont_def (RUNNING->RUNNING),]: cont_def(162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master) (RUNNING->RUNNING) to RUNNING, but already RUNNING
2016-11-10T20:24:04Z [INFO] Sending task change module="eventhandler" event="TaskChange: arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa -> RUNNING, Known Sent: NONE" change="TaskChange: arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa -> RUNNING, Known Sent: NONE"
2016-11-10T20:24:05Z [INFO] Task change event module="TaskEngine" event="{TaskArn:arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa Status:STOPPED Reason: SentStatus:RUNNING}"
2016-11-10T20:24:05Z [INFO] Error retrieving stats for container be6256dc8dffaf209d165f7e9371a82affbfcbfe81676257000b46775633b077: context canceled
2016-11-10T20:24:05Z [INFO] Adding event module="eventhandler" change="ContainerChange: arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa cont_def -> STOPPED, Exit 139, , Known Sent: RUNNING"
2016-11-10T20:24:05Z [INFO] Adding event module="eventhandler" change="TaskChange: arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa -> STOPPED, Known Sent: RUNNING"
2016-11-10T20:24:05Z [INFO] Container be6256dc8dffaf209d165f7e9371a82affbfcbfe81676257000b46775633b077 is terminal, stopping stats collection
2016-11-10T20:24:05Z [INFO] Sending container change module="eventhandler" event="ContainerChange: arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa cont_def -> STOPPED, Exit 139, , Known Sent: RUNNING" change="ContainerChange: arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa cont_def -> STOPPED, Exit 139, , Known Sent: RUNNING"
2016-11-10T20:24:05Z [INFO] Sending task change module="eventhandler" event="TaskChange: arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa -> STOPPED, Known Sent: RUNNING" change="TaskChange: arn:aws:ecs:eu-central-1:162782911101:task/56121f8d-abfa-4f8d-85a4-1ac8b16471fa -> STOPPED, Known Sent: RUNNING"
2016-11-10T20:24:13Z [INFO] Saving state! module="statemanager"
2016-11-10T20:34:13Z [INFO] Creating poll dialer, host: ecs-t-1.eu-central-1.amazonaws.com
2016-11-10T20:42:37Z [INFO] Saving state! module="statemanager"
2016-11-10T20:42:37Z [INFO] Pulling container module="TaskEngine" task="task_def:2 arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7, Status: (NONE->RUNNING) Containers: [cont_def (NONE->RUNNING),]" container="cont_def(162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master) (NONE->RUNNING)"
2016-11-10T20:42:37Z [INFO] Updating container reference cont_def in Image State - sha256:9b90ff41179f2a073529ddc4659605b69d2d8cf80f07f5f9ac76a98371cbd1ce
2016-11-10T20:42:37Z [INFO] Creating container module="TaskEngine" task="task_def:2 arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7, Status: (NONE->RUNNING) Containers: [cont_def (PULLED->RUNNING),]" container="cont_def(162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master) (PULLED->RUNNING)"
2016-11-10T20:42:37Z [INFO] Created container name mapping for task task_def:2 arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7, Status: (NONE->RUNNING) Containers: [cont_def (PULLED->RUNNING),] - cont_def(162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master) (PULLED->RUNNING) -> ecs-task_def-2-contdef-ceb8b6a8ebfae19ed501
2016-11-10T20:42:37Z [INFO] Saving state! module="statemanager"
2016-11-10T20:42:37Z [INFO] Created docker container for task task_def:2 arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7, Status: (CREATED->RUNNING) Containers: [cont_def (CREATED->RUNNING),]: cont_def(162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master) (CREATED->RUNNING) -> fcf7b2cd52772970cdc3cb2e20cc0305d7952e07b4c471383e92ec3283fccb69
2016-11-10T20:42:37Z [INFO] Starting container module="TaskEngine" task="task_def:2 arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7, Status: (CREATED->RUNNING) Containers: [cont_def (CREATED->RUNNING),]" container="cont_def(162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master) (CREATED->RUNNING)"
2016-11-10T20:42:38Z [INFO] Task change event module="TaskEngine" event="{TaskArn:arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 Status:RUNNING Reason: SentStatus:NONE}"
2016-11-10T20:42:38Z [INFO] Adding event module="eventhandler" change="ContainerChange: arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 cont_def -> RUNNING, Ports [{5000 5000 0.0.0.0 0}], Known Sent: NONE"
2016-11-10T20:42:38Z [INFO] Adding event module="eventhandler" change="TaskChange: arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 -> RUNNING, Known Sent: NONE"
2016-11-10T20:42:38Z [INFO] Sending container change module="eventhandler" event="ContainerChange: arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 cont_def -> RUNNING, Ports [{5000 5000 0.0.0.0 0}], Known Sent: NONE" change="ContainerChange: arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 cont_def -> RUNNING, Ports [{5000 5000 0.0.0.0 0}], Known Sent: NONE"
2016-11-10T20:42:38Z [INFO] Redundant container state change for task task_def:2 arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7, Status: (RUNNING->RUNNING) Containers: [cont_def (RUNNING->RUNNING),]: cont_def(162782911101.dkr.ecr.eu-central-1.amazonaws.com/repo_offpop_wrapper1:tr1master) (RUNNING->RUNNING) to RUNNING, but already RUNNING
2016-11-10T20:42:38Z [INFO] Sending task change module="eventhandler" event="TaskChange: arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 -> RUNNING, Known Sent: NONE" change="TaskChange: arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 -> RUNNING, Known Sent: NONE"
2016-11-10T20:42:39Z [INFO] Task change event module="TaskEngine" event="{TaskArn:arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 Status:STOPPED Reason: SentStatus:RUNNING}"
2016-11-10T20:42:39Z [INFO] Error retrieving stats for container fcf7b2cd52772970cdc3cb2e20cc0305d7952e07b4c471383e92ec3283fccb69: context canceled
2016-11-10T20:42:39Z [INFO] Adding event module="eventhandler" change="ContainerChange: arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 cont_def -> STOPPED, Exit 139, , Known Sent: RUNNING"
2016-11-10T20:42:39Z [INFO] Adding event module="eventhandler" change="TaskChange: arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 -> STOPPED, Known Sent: RUNNING"
2016-11-10T20:42:39Z [INFO] Container fcf7b2cd52772970cdc3cb2e20cc0305d7952e07b4c471383e92ec3283fccb69 is terminal, stopping stats collection
2016-11-10T20:42:39Z [INFO] Sending container change module="eventhandler" event="ContainerChange: arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 cont_def -> STOPPED, Exit 139, , Known Sent: RUNNING" change="ContainerChange: arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 cont_def -> STOPPED, Exit 139, , Known Sent: RUNNING"
2016-11-10T20:42:39Z [INFO] Sending task change module="eventhandler" event="TaskChange: arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 -> STOPPED, Known Sent: RUNNING" change="TaskChange: arn:aws:ecs:eu-central-1:162782911101:task/edebd1b6-3f24-4d4e-9643-c6e80e95d2c7 -> STOPPED, Known Sent: RUNNING"
2016-11-10T20:42:47Z [INFO] Saving state! module="statemanager"
2016-11-10T20:49:36Z [INFO] Creating poll dialer, host: ecs-a-1.eu-central-1.amazonaws.com
2016-11-10T20:50:13Z [INFO] No eligible images for deletion for this cleanup cycle
2016-11-10T20:50:13Z [INFO] End of eligible images for deletion
=================
interesting that everything works as expected with my other docker image

**Comment by YurgenUA** [comment]
forgot to mention that everything works as expected with my other docker image

**Comment by YurgenUA** [comment]
my fault. Closing this issue...
=======
when I run my docker image with 'docker run image:tag' (detached mode, without -it), I saw the exception in my code:
Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at Program.Main(String[] args)

**Comment by sandeep1512** [comment]
Hi Yurgen,
I have similar issue, I dint understand your above comment, Could you please help how to troubleshoot his issue?
Error:
2017-10-18T18:06:39Z [INFO] Saving state! module="statemanager"
2017-10-18T18:06:44Z [INFO] Pulling container serially module="TaskEngine" task="creditoffers-adminui-qa:10 arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5, Status: (NONE->RUNNING) Containers: [creditoffer-admin-UI (NONE->RUNNING),]" container="creditoffer-admin-UI(dockyard.cloud.capitalone.com/creditoffers/creditoffers-admin-ui:dea0bc67f6c00347deffa7e595f0135bc59193e1) (NONE->RUNNING)"
2017-10-18T18:06:44Z [INFO] Updating container reference creditoffer-admin-UI in Image State - sha256:3a781f6d6ab8e7e13b4c651bde4d5c4fff752c5654f79273dae7a54083561af9
2017-10-18T18:06:44Z [INFO] Saving state! module="statemanager"
2017-10-18T18:06:44Z [INFO] Creating container module="TaskEngine" task="creditoffers-adminui-qa:10 arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5, Status: (NONE->RUNNING) Containers: [creditoffer-admin-UI (PULLED->RUNNING),]" container="creditoffer-admin-UI(dockyard.cloud.capitalone.com/creditoffers/creditoffers-admin-ui:dea0bc67f6c00347deffa7e595f0135bc59193e1) (PULLED->RUNNING)"
2017-10-18T18:06:44Z [INFO] Created container name mapping for task creditoffers-adminui-qa:10 arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5, Status: (NONE->RUNNING) Containers: [creditoffer-admin-UI (PULLED->RUNNING),] - creditoffer-admin-UI(dockyard.cloud.capitalone.com/creditoffers/creditoffers-admin-ui:dea0bc67f6c00347deffa7e595f0135bc59193e1) (PULLED->RUNNING) -> ecs-creditoffers-adminui-qa-10-creditoffer-admin-UI-86f482ca98f2c4d70400
2017-10-18T18:06:44Z [INFO] Saving state! module="statemanager"
2017-10-18T18:06:44Z [INFO] Created docker container for task creditoffers-adminui-qa:10 arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5, Status: (CREATED->RUNNING) Containers: [creditoffer-admin-UI (CREATED->RUNNING),]: creditoffer-admin-UI(dockyard.cloud.capitalone.com/creditoffers/creditoffers-admin-ui:dea0bc67f6c00347deffa7e595f0135bc59193e1) (CREATED->RUNNING) -> 8c3fc43b38db987b03fb089474a07b3a6e51890936d70669d79e3caf0f316437
2017-10-18T18:06:44Z [INFO] Starting container module="TaskEngine" task="creditoffers-adminui-qa:10 arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5, Status: (CREATED->RUNNING) Containers: [creditoffer-admin-UI (CREATED->RUNNING),]" container="creditoffer-admin-UI(dockyard.cloud.capitalone.com/creditoffers/creditoffers-admin-ui:dea0bc67f6c00347deffa7e595f0135bc59193e1) (CREATED->RUNNING)"
2017-10-18T18:06:45Z [INFO] Task change event module="TaskEngine" event="{TaskArn:arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 Status:RUNNING Reason: SentStatus:NONE}"
2017-10-18T18:06:45Z [INFO] Adding event module="eventhandler" change="ContainerChange: arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 creditoffer-admin-UI -> RUNNING, Ports [{8000 8000 0.0.0.0 0}], Known Sent: NONE"
2017-10-18T18:06:45Z [INFO] Adding event module="eventhandler" change="TaskChange: arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 -> RUNNING, Known Sent: NONE"
2017-10-18T18:06:45Z [INFO] Sending container change module="eventhandler" event="ContainerChange: arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 creditoffer-admin-UI -> RUNNING, Ports [{8000 8000 0.0.0.0 0}], Known Sent: NONE" change="ContainerChange: arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 creditoffer-admin-UI -> RUNNING, Ports [{8000 8000 0.0.0.0 0}], Known Sent: NONE"
2017-10-18T18:06:45Z [INFO] Redundant container state change for task creditoffers-adminui-qa:10 arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5, Status: (RUNNING->RUNNING) Containers: [creditoffer-admin-UI (RUNNING->RUNNING),]: creditoffer-admin-UI(dockyard.cloud.capitalone.com/creditoffers/creditoffers-admin-ui:dea0bc67f6c00347deffa7e595f0135bc59193e1) (RUNNING->RUNNING) to RUNNING, but already RUNNING
2017-10-18T18:06:45Z [INFO] Sending task change module="eventhandler" event="TaskChange: arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 -> RUNNING, Known Sent: NONE" change="TaskChange: arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 -> RUNNING, Known Sent: NONE"
2017-10-18T18:06:45Z [INFO] Task change event module="TaskEngine" event="{TaskArn:arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 Status:STOPPED Reason: SentStatus:RUNNING}"
2017-10-18T18:06:45Z [INFO] Error retrieving stats for container 8c3fc43b38db987b03fb089474a07b3a6e51890936d70669d79e3caf0f316437: context canceled
2017-10-18T18:06:45Z [INFO] Adding event module="eventhandler" change="ContainerChange: arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 creditoffer-admin-UI -> STOPPED, Exit 2, , Known Sent: RUNNING"
2017-10-18T18:06:45Z [INFO] Adding event module="eventhandler" change="TaskChange: arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 -> STOPPED, Known Sent: RUNNING"
2017-10-18T18:06:45Z [INFO] Container 8c3fc43b38db987b03fb089474a07b3a6e51890936d70669d79e3caf0f316437 is terminal, stopping stats collection
2017-10-18T18:06:45Z [INFO] Sending container change module="eventhandler" event="ContainerChange: arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 creditoffer-admin-UI -> STOPPED, Exit 2, , Known Sent: RUNNING" change="ContainerChange: arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 creditoffer-admin-UI -> STOPPED, Exit 2, , Known Sent: RUNNING"
2017-10-18T18:06:45Z [INFO] Sending task change module="eventhandler" event="TaskChange: arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 -> STOPPED, Known Sent: RUNNING" change="TaskChange: arn:aws:ecs:us-east-1:685250009713:task/d1766b29-c0c9-43f9-a32a-5c4b222746d5 -> STOPPED, Known Sent: RUNNING"

**Comment by MathiasLund** [comment]
@YurgenUA did you find a solution? I am having same problem.
