### ISSUE TITLE
Intermittent unit test failure on TestSendsEventsContainerDifferences()

### ISSUE THREAD

**Issue by liwenwu-amazon** [aws/amazon-ecs-agent#663]
On Windows Platform, unit-test sometimes failed on TestSendsEventsContainerDifferences(). Here is the output of failure:

```
017-01-09T23:10:30Z [INFO] Adding event module="eventhandler" change="ContainerChange: notreplaced1 containerName -> RUNNING"
2017-01-09T23:10:30Z [INFO] Adding event module="eventhandler" change="ContainerChange: notreplaced1 containerName -> STOPPED"
2017-01-09T23:10:30Z [INFO] Sending container change module="eventhandler" event="ContainerChange: notreplaced1 containerName -> RUNNING" change="ContainerChange: notreplaced1 containerName -> RUNNING"
panic: test timed out after 25s



goroutine 49 [running]:
panic(0x75e0a0, 0xc042142860)
	c:/go/src/runtime/panic.go:500 +0x1af
testing.startAlarm.func1()
	c:/go/src/testing/testing.go:918 +0x112
	created by time.goFunc
	c:/go/src/time/sleep.go:154 +0x4b


	goroutine 1 [chan receive]:
testing.(*T).Run(0xc04207e6c0, 0x7ed9c8, 0x23, 0x8131b8, 0xc04208fd01)
	c:/go/src/testing/testing.go:647 +0x31d
testing.RunTests.func1(0xc04207e6c0)
	c:/go/src/testing/testing.go:793 +0x74
testing.tRunner(0xc04207e6c0, 0xc04208fe00)
	c:/go/src/testing/testing.go:610 +0x88
testing.RunTests(0x813468, 0x9a4420, 0x7, 0x7, 0x40e3f9)
	c:/go/src/testing/testing.go:799 +0x2fc
testing.(*M).Run(0xc04208fec8, 0x482d59)
	c:/go/src/testing/testing.go:743 +0x8c
main.main()
	github.com/aws/amazon-ecs-agent/agent/eventhandler/_test/_testmain.go:66 +0xcd



	goroutine 4 [semacquire]:
sync.runtime_notifyListWait(0xc042007990, 0x0)
	c:/go/src/runtime/sema.go:267 +0x130
sync.(*Cond).Wait(0xc042007980)
	c:/go/src/sync/cond.go:57 +0x87
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc0420428a0, 0x0)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x9e
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc0420428a0)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x3a
	created by github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.newAsyncLoopLogger
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x9d


	goroutine 5 [semacquire]:
sync.runtime_notifyListWait(0xc042007b90, 0x0)
	c:/go/src/runtime/sema.go:267 +0x130
sync.(*Cond).Wait(0xc042007b80)
	c:/go/src/sync/cond.go:57 +0x87
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc0420429c0, 0x0)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x9e
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc0420429c0)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x3a
	created by github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.newAsyncLoopLogger
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x9d

	goroutine 6 [semacquire]:
sync.runtime_notifyListWait(0xc0420fa150, 0x13)
	c:/go/src/runtime/sema.go:267 +0x130
sync.(*Cond).Wait(0xc0420fa140)
	c:/go/src/sync/cond.go:57 +0x87
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc042042b40, 0x0)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x9e
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc042042b40)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x3a
	created by github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog.newAsyncLoopLogger
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x9d


	goroutine 15 [semacquire]:
sync.runtime_Semacquire(0xc04218c228)
	c:/go/src/runtime/sema.go:47 +0x37
sync.(*Mutex).Lock(0xc04218c224)
	c:/go/src/sync/mutex.go:85 +0xd7
github.com/aws/amazon-ecs-agent/agent/eventhandler.addEvent(0xc04211c500, 0x98aba0, 0xc04217a320)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/task_handler.go:60 +0x148
github.com/aws/amazon-ecs-agent/agent/eventhandler.AddContainerEvent(0x7e362f, 0xc, 0x7e3bb8, 0xd, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/task_handler.go:37 +0x102
github.com/aws/amazon-ecs-agent/agent/eventhandler.TestSendsEventsContainerDifferences(0xc04207eb40)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/handler_test.go:132 +0x5c9
testing.tRunner(0xc04207eb40, 0x8131b8)
	c:/go/src/testing/testing.go:610 +0x88
	created by testing.(*T).Run
	c:/go/src/testing/testing.go:646 +0x2f3



	goroutine 16 [chan send]:
github.com/aws/amazon-ecs-agent/agent/eventhandler.TestSendsEventsContainerDifferences.func1(0x7bbb40, 0xc04216cf00)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/handler_test.go:128 +0x47
reflect.Value.call(0x75d220, 0xc04217a350, 0x13, 0x7e01d4, 0x4, 0xc04218c2c0, 0x1, 0x1, 0xc042175af8, 0x50ae4a, ...)
	c:/go/src/reflect/value.go:434 +0x5cf
reflect.Value.Call(0x75d220, 0xc04217a350, 0x13, 0xc04218c2c0, 0x1, 0x1, 0x50ba51, 0xc042175b08, 0xc042175b18)
	c:/go/src/reflect/value.go:302 +0xab
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/golang/mock/gomock.(*Call).call.func1()
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/golang/mock/gomock/call.go:213 +0x71
github.com/aws/amazon-ecs-agent/agent/vendor/github.com/golang/mock/gomock.(*Controller).Call(0xc04218c140, 0x79efa0, 0xc04217a320, 0x7e99af, 0x1a, 0xc04217a530, 0x1, 0x1, 0x0, 0x0, ...)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/vendor/github.com/golang/mock/gomock/controller.go:136 +0x2a4
github.com/aws/amazon-ecs-agent/agent/api/mocks.(*MockECSClient).SubmitContainerStateChange(0xc04217a320, 0x7e362f, 0xc, 0x7e3bb8, 0xd, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/api/mocks/api_mocks.go:177 +0x108
github.com/aws/amazon-ecs-agent/agent/eventhandler.SubmitTaskEvents.func1(0x0, 0x0)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/task_handler.go:113 +0xb48
github.com/aws/amazon-ecs-agent/agent/utils.RetryWithBackoff(0x987d80, 0xc0421860f0, 0xc042175f48, 0x0, 0x0)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/utils/utils.go:112 +0x32
github.com/aws/amazon-ecs-agent/agent/eventhandler.SubmitTaskEvents(0xc04218c220, 0x98aba0, 0xc04217a320)
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/task_handler.go:157 +0x10f
	created by github.com/aws/amazon-ecs-agent/agent/eventhandler.addEvent
	C:/Users/ADMINI~1/AppData/Local/Temp/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/task_handler.go:68 +0x1f1
	FAIL        github.com/aws/amazon-ecs-agent/agent/eventhandler              26.149s

 
 ```

**Comment by richardpen** [comment]
This has been released in [v1.14.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.14.1)
